### ISSUE TITLE
Snatcher - Issues with audio and freeze

### ISSUE THREAD

**Issue by pyrsmk** [ekeeke/Genesis-Plus-GX#539] opened 2024-02-10 13:20 UTC
Hello,

I'm experiencing blocking issues with Snatcher in the Act 2 (when meeting the group of snatchers in the hospital). I suddenly lose audio. And after some time, when a scene seems to load, it just freezes on a black screen.

Version of Snatcher : Europe (also tried USA version with the same state)
Platform : 3DS on Retroarch

I'm available to output any debug messages or anything if needed.

**Comment by ekeeke** [comment] 2024-02-10 18:09
A copy of the internal backup ram file (.brm) would help to try reproducing your issue.

I remember finishing this game years ago in this emulator (on Wii) without encountering any issue but it's possible some on the recent changes to improve CD hardware emulatipn accuracy introduced some regression or exposed an emulation flaw that was hidden before.

I also know this game is very picky about audio tracks length so make sure you are using a verified CD image (cue+bin preferably).

**Comment by pyrsmk** [comment] 2024-02-10 20:16
Unfortunately, I did not find an image with a CRC for all the track files. But I tried the Europe and USA versions with the same state file, and it fails exactly the same way. So the integrity is should be ok ?

I can provide the state file of the moment before the audio bug, and also a .srm before running the command "Reconstruct corpse".

I did not find how to get the .brm file, how can I dump it ?

Here's the .state and .srm files : https://fromsmash.com/snatcher

**Comment by ekeeke** [comment] 2024-02-11 08:08
>Unfortunately, I did not find an image with a CRC for all the track files. But I tried the Europe and USA versions with the same state file, and it fails exactly the same way. So the integrity should be ok ?

No, I mean there are several images of Snatcher floating around that have incorrect audio track lengths (usually coming with ISO file and separated wav files). You have to make sure the files you are using comes as CUE+BIN and is tagged from a verified dump database (like Redump) 

> I did not find how to get the .brm file, how can I dump it ?

The brm files are usually in retroarch saves directory (or in the same directory as game file if no saves directory is configured). There should be one for the external cartridge back-up RAM (cart.brm) and three for each region Mega-CD internal back-up RAM (scd_E.brm, scd_U.brm, scd_J.brm). If per-game saves is enabled in core settings, there would be also cart_xxxx.brm and xxxx.brm files, with xxxx set to the game name, respectively corresponding to external cartridge and internal Mega-CD back-up RAM files (one per Mega-CD game).

> Here's the .state and .srm files : https://fromsmash.com/snatcher

This is not a valid Genesis Plus GX state file (it should start with "GPGX" header) and Genesis Plus GX does not produce .srm files for Mega-CD games. 
Are you sure you are using Genesis Plus GX core and not another Retroarch core that supports Mega-CD (like Picodrive) ?
From memory, Genesis Plus GX is quite slow and therefore not much enjoyable on original 3DS so that makes me wonder...

**Comment by pyrsmk** [comment] 2024-02-11 10:38
Thanks for mentioning Redump, that's what I needed. I just verified all the CRC checksums for the files and everything is good. Is it good enough to know that the files are good ? I'm not sure if MD5/SHA1 checks would add anything.

> Are you sure you are using Genesis Plus GX core and not another Retroarch core that supports Mega-CD (like Picodrive) ?

I'm really using Genesis Plus GX, but, indeed, I was using Picodrive before it (but not with Snatcher). I'm surprised as it seems that this is really the state file being used in Retroarch to handle my save from Snatcher. 

Anyway, I managed to find the BRM filles you wanted : https://fromsmash.com/snatcher2

> From memory, Genesis Plus GX is quite slow (and therefore not much enjoyable) on original 3DS so that makes me wonder...

I have a New 3DS, it has better performance. I even can run PS1 emulation on it ☺️

**Comment by ekeeke** [comment] 2024-02-11 12:17
Loaded your save file in win32 latest core (from [here ](https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genesis_plus_gx_libretro.dll)) and selected "Reconstruct corpse", it seems to work fine for me

https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/e078522e-feb2-4e23-878e-fa45bc525470

**Comment by pyrsmk** [comment] 2024-02-11 14:12
In fact you need to wait for the whole reconstruction phase until the protagonist are being shot by the snatchers group. The audio just after that. And if you have the patience to wait the whole scene, at some point the screen is black and nothing is happening anymore.

**Comment by ekeeke** [comment] 2024-02-11 18:38
Looks to be fine here, I verified there was no audio issues after the attack of the snatchers 
https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/b87977fe-ca1c-4ecb-a146-cba6116997ac

I also waited until the end of the cutscene and everything was fine. The screen indeed stays black for a while after the explosion but there are some dialogues betwen Gillian and Meta Gear until the dialog boxes appear again, see recording below
https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/230a2fc7-e076-474f-b25d-333f72998569

I see two possibilities for your issue since you confirmed you were using a redump verified CD image:
- the issue is caused by one the core settings you are using that is not default setting and results in non-accurate behavior (like CD latency or CPU overclock) or by retroarch run-ahead feature (which is a kind of hack and can cause emulation issues)
- the 3ds core is using an outdated version of the emulator

Either ways, I'm closing this as it seems there are no issues with the current emulation core.

**Closed by ekeeke** 2024-02-11 18:38 UTC

**Comment by pyrsmk** [comment] 2024-02-11 18:42
Thank you very much to have investigated the issue so quickly.

This is probably "good" news as I just need to find what's causing this 😅

Do you think that the arch could cause this? Or even the platform itself?

**Comment by ekeeke** [comment] 2024-02-11 18:43
Sorry, no idea  about that, I'm not a Retroarch developer
