### ISSUE TITLE
[libretro] Disk swapping

### ISSUE THREAD

**Issue by nosh01** [ekeeke/Genesis-Plus-GX#51] opened 2015-05-29 16:10 UTC
Is the automatic disk swapping feature of genesis-plus-gx exposed to libretro?

**Comment by ekeeke** [comment] 2015-05-29 16:23
Nope.

This can be handled in "retro_load_game" by not reseting emulation when virtual CD tray is "open" (like it is done in genesis plus gx wii version) and just "load" the new disk image but the core cannot control what the frontend (retroarch) is doing when new content is loaded so if retroarch resets some stuff on its side, it might not work.

**Comment by fr500** [comment] 2015-05-29 16:35
Would it be possible to use the disk control interface for this purpose? It allows the frontend to "append" additional images and change them, it also has tray control (disk needs to be ejected first to swap disks).

That's what we do in mednafen-psx at least.

**Comment by ekeeke** [comment] 2015-05-29 16:41
Probably but I have no idea how this works. Automatic disk swapping is a little bit more intuitive though as it does not need user to eject the disk manually but simply to load the new disk image when prompted by the game (in Sega CD, tray is opened by software when necessary so an emulator can detect it)

**Comment by fr500** [comment] 2015-05-29 16:44
Since the core uses need_fullpath it should be relatively easy, I will try to implement the libretro interface and send a PR if I succeed

**Comment by ekeeke** [comment] 2015-05-29 17:22
I tried to implement automatic disk swapping but, no matter what I do, retroarch will always completely resets the core (all data seem to be reseted to zero) when loading content so that feature is not possible via libretro.

Manual disk swapping should be possible using libretro dedicated interface though as said above by fr500. I will be waiting for the PR.

**Comment by newoski** [comment] 2015-08-14 19:02
Wouldn't it be possible via the m3u methodology that Mednafen supports? The Beetle/Mednafen PSX core supports it as described below:
http://wiki.libretro.com/index.php?title=Beetle/Mednafen_PSX

Usage
Mednafen can load CD-ROM games from a ripped/dumped copy of the disc, such as CUE+BIN. Additionally there is support for CloneCD "CCD/IMG/SUB" [1] rips, and cdrdao "TOC" files [2].

CUE sheet example:

FILE "Mega Man 8 (USA) (Track 1).bin" BINARY
TRACK 01 MODE2/2352
INDEX 01 00:00:00
FILE "Mega Man 8 (USA) (Track 2).bin" BINARY
TRACK 02 AUDIO
INDEX 00 00:00:00
INDEX 01 00:02:00
FILE "Mega Man 8 (USA) (Track 3).bin" BINARY
TRACK 03 AUDIO
INDEX 00 00:00:00
INDEX 01 00:02:00

The recommended method to play games consisting of more than one CD, is to create an M3U file(plain-text, ".m3u" extension), and enter the filenames of the CUE/TOC/CCD files, one per line. Load the M3U file instead of the CUE/TOC/CCD file and swap disks from the core disk options menu (under Options), make sure to cycle tray status before attempting to change disks.

M3U playlist example:


Final Fantasy IX (USA) (Disc 1) (v1.1).cue
Final Fantasy IX (USA) (Disc 2) (v1.1).cue
Final Fantasy IX (USA) (Disc 3) (v1.1).cue
Final Fantasy IX (USA) (Disc 4) (v1.1).cue

An alternative is to append disks to the current playlist via RGUI. A side advantage of the M3U method vs. the Append Disk method is that memory cards are named after the playlist itself, so you don't have different saves for different disks of the same game.

Jump up ↑ untested
Jump up ↑ untested

**Comment by ekeeke** [comment] 2015-08-14 21:56
It could be done but it would require rewriting the whole CDD implementation in Genesis Plus GX to allow having multiple CD images opened & loaded simultaneously during emulation. It seems to be a way too much complex solution for a very simple problem that should be handle by the frontend in my opinion, not the core. 

For example, this is how disc swap is done currently in standalone Genesis Plus GX.
When a Mega CD game requires disk swapping, it usually sends an "Open Tray" command to the CD hardware. The emulator catches this command and if you try to load another CD file when the virtual tray is seen as "open", it will not reset the system but instead refresh the virtual CD loaded, just like what would happen on real hardware.

This is sadly not possible with libretro frontends, but hopefully there seems to be a disc swap feature available libretro API that can be used for this, which is what needs to be implemented as discussed in above posts.

**Comment by newoski** [comment] 2015-08-14 22:04
Hmmm... From all of using RetroArch as part of a larger Arcade Frontend, like HyperSpin, this just doesn't work. 

):

**Comment by ekeeke** [comment] 2015-08-14 22:06
What "doesn't work" ?

**Comment by newoski** [comment] 2015-08-14 22:08
Before I answer that question, so I can best answer it, are you familiar with HyperSpin & RocketLauncher/HyperLaunch?

**Comment by ekeeke** [comment] 2015-08-14 22:45
Absolutely... not

**Comment by Warriors-Blade** [comment] 2015-08-22 05:03
ekeeke, you think if you went and talked to the RA devs in IRC or made a issue in the retroarch github page you might be able to get this issue underway with their help?

just a suggestion.

**Comment by newoski** [comment] 2015-08-22 13:00
I posted on the main RA github last night. I'll check out the IRC channel, too to try to figure out if this is a core or RA issue

**Comment by ekeeke** [comment] 2015-08-23 17:23
I don't think you understood what has been said. Read the discussion above. Off course, disc swapping does not work. It has yet to be implemented in the Genesis Plus GX libretro port and fr500 said he will eventually try to do it. That's all.

**Comment by newoski** [comment] 2015-08-23 17:27
Ah, I misunderstood. I understand now. Thanks

**Comment by fr500** [comment] 2015-09-28 05:06
I actually was looking at this but I got distracted with some other things.
I don't think it's trivial to implement, I was wrong before. It seems mednafen keeps track of the set of disks that are to be loaded (via the M3U mechanism, adding disks on the fly was only implemented in the libretro port https://github.com/libretro/beetle-psx-libretro/blob/master/libretro.cpp#L2152).

The disk interface in the frontend controls the state of the tray,  and what disk is selected. It also defines a few callbacks that can be used to build the "list of disks:
https://github.com/libretro/RetroArch/blob/master/libretro.h#L1672

It works like this: 
- You load content normally
- You append a disk, it's added to a list, the disk being played is still disk #1
- When the time comes you can then go and eject the disk, select disk #2 and close the tray

Then the core should do whatever it needs internally to swap the disk.

From what I understand, the frontend can ask to eject via:
    retro_set_eject_state_t set_eject_state;
It can ask the core to change the current disk using:
    retro_set_image_index_t set_image_index;
The frontend can tell the core that there will be an additional disk in the set and then add the info to the list via these:
    retro_add_image_index_t add_image_index;
    retro_replace_image_index_t replace_image_index;

So yeah it's definitely doable but it sounds like it requires quite a bit of work.

BTW, just to clear up I'm not asking you to implement this, I said I would try but I don't know were to start tbh.

**Comment by davidj1987** [comment] 2015-12-03 19:32
Doesn't picodrive-libretro support disc swapping?

**Comment by klepp0906** [comment] 2017-11-06 20:22
was this ever handled? Aka a means to swap sega cd discs?  Personally I use steamlink to play scd games via RA so adding more than the  shortcut to the initial disc is just bad juju.

I'd like to be able to simply shortcut into the RA interface and swap discs via navigation when its called for.

I know psx can be done via m3u or psp format (both are which are also un ideal to me) and would prefer being able to simply navigate to the file.

Havent seen anyone post in awhile so what do you guys w/ a steam link do about multi disc SCD games at current?

**Comment by mccorkled** [comment] 2018-10-27 14:18
Been nearly a year now. Curious as well if this has been worked on. 

Thank you.

**Comment by ekeeke** [comment] 2020-05-30 13:32
Support for disk control interface and m3u file list in libretro port was added by https://github.com/ekeeke/Genesis-Plus-GX/commit/82c4821503b576faf38b39ee10f7139748f8671c

It was simple enough to implement and,contrary to what I initially thought, no core changes were required.

There are a few limitations I noticed though with Retroarch 1.8.5 (maybe fixed in later versions ?):

1/ disk control interface only let you add a new disk when the current disk status is set to 'not ejected', which can be problematic with Sega CD games since the disk tray is automatically opened by the BIOS when disk swapping is required so, when you want to manually add disks, you either need to do it in the CD player interface on boot (then swap back to the first disk) before the game is started, or, when asked by the game, you first need to close the disk tray, then add the new disk, then close disk tray again since it was re-opened by retroarch when adding new disk. Note that the latter won't work with some games (like Sherlock Holmes 2) which automatically check the disk as soon as disk tray is closed and re-open disk tray automatically if it is not the expected disk. Obviously, this is easily fixable by using m3u file list to automatically add all disks when the game is loaded, but it still can be annoying for people who want to use Retroarch interface to add new disks.

2/ although "m3u" file extension was added in the "valid_extensions" field returned by retro_get_system_info function ( see https://github.com/ekeeke/Genesis-Plus-GX/blob/master/libretro/libretro.c#L2190 ), it seems like these infos are completely ignored by Retroarch as it is impossible to load a m3u file in Genesis Plus GX core unless you modify the "genesis_plus_gx_libretro.info" file located under /info in your Retroarch installation to modify the supported extension list in there. Again, I don't know if this is expected behavior, but it seems quite odd to me that you have to rely on external infos to let you load a file supported by the core.

**Closed** 2020-05-30 13:46 UTC
Labels: enhancement, libretro

**Comment by ekeeke** [comment] 2020-05-30 13:47
Added https://github.com/ekeeke/Genesis-Plus-GX/commit/f0429f1637b72cbb78628a37e598dd4e2a8e90c4 to fix a compilation issue

**Comment by prataczak** [comment] 2020-06-21 08:33
I googled and found this issue, and I followed your instructions of altering the info file, and the m3u will load, but the game itself will not. Tried with 'Dracula Unleashed' Disc 2 (so that I could change to disc 1 when prompted). Nothing but black screen.

Are these updates in the current core?

**Comment by ekeeke** [comment] 2020-06-21 10:03
Afaik, the required changes have not yet been backported in libretro repository so it won't work if you are using core downloaded from retroarch, you will need to use the core (.dll) built in this repository but it's windows 32-bit only.

Also, you shouldn't put absolute filepaths in m3u file, it won't work. m3u file should be in same path as the the CD image files and list only relative filenames. 

Lastly, you are better listing files in disc order, even if it works fine, as retroarch disk interface only shows you disk indexes, not filenames.

**Comment by prataczak** [comment] 2020-06-21 10:29
Thanks for the reply. Only reason I tried absolute paths is because the 'Dolphin' emulator required them in order to get m3u to work via command line (loading an m3u through the GUI did not require the absolute paths).

The short answer for the reason I put them in reverse order for disc 2 is that I only use keyboard hotkey shortcuts to change disc, I never use the menu unless I have to. :)

I have little bit of experience compiling. If it's not too much trouble, can you point me in the right direction on how to produce a 64 bit version of it?

**Comment by prataczak** [comment] 2020-06-21 11:07
Never mind, figured it out. It works great, thanks for adding this!

**Comment by bebess** [comment] 2021-04-28 15:00
sorry i dont understand where to find the new dll core ?
do i need a retroarch 32bit version to run it ?

or maybe is it in the core downloader of retroarch ?

sorry i feel so noob ^^

**Comment by Sanaki** [comment] 2021-04-28 21:14
Core downloader should pull it fine, and it won't require 32-bit.
