### ISSUE TITLE
Ghostbusters Sound Test not working

### ISSUE THREAD

**Issue by ArcadeTV** [ekeeke/Genesis-Plus-GX#335] opened 2020-10-08 07:10 UTC
While making a MSU MD patch for Ghostbusters I came across a non-MSU-MD-ralated issue:
In Ghostbusters (W) (REV01) [!].bin (792DF93B) the Sound Test is not working. In other emulators and real hardware the same rom plays fine.

**Comment by ekeeke** [comment] 2020-10-08 17:58
What version of the emulator are you using ( retroarch build ? some other build ?) ?
If you are using it in retroarch, which YM2612 core are you using ? MAME or nuked ?

I can not reproduce this issue with either REV00 or REV01 version of this game in my own win32 SDL test build (based on current github codebase), sound test (BGM and SFX) works just fine when I press B button (A & START buttons seem to do nothing and C seems to stop BGM).

**Comment by ArcadeTV** [comment] 2020-10-08 20:40
Sorry for not providing that info in the first place...
54b946c | RetroArch | Win64

I've been cycling through the sound drivers, both mame and nuked variants. I don't suspect the sound driver to fail, it might be the implementation of the sound test in the rom itself since I'm hijacking a function for my MSU-MD driver hack which also fails, though I can see the program flow is correct.

**Comment by ekeeke** [comment] 2020-10-11 14:11
>54b946c | RetroArch | Win64

I don't have a 64-bit build so I guess you compiled it yourself but I tested latest libretro win32 build (available from here: https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genesis_plus_gx_libretro.dll) in Retroarch and could not reproduce your issue

See attached recording file
[Ghostbusters (World) (v1.1)-201011-160233.mkv.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/5361218/Ghostbusters.World.v1.1.-201011-160233.mkv.zip)

Maybe you have some Retroarch-specific feature like rewind, runahead or CPU overclock enabled that would break this particular game, I don't really know.

**Comment by ekeeke** [comment] 2020-10-30 12:37
Closing this for now as I can not reproduce it.

**Closed by ekeeke** 2020-10-30 12:37 UTC
Labels: invalid
