### ISSUE TITLE
Master System mappers in SG-1000 & SG-1000 II emulation?

### ISSUE THREAD

**Issue by Creeper25** [ekeeke/Genesis-Plus-GX#450] opened 2022-08-09 19:46 UTC
I forced Super Boy I., Super Boy II., Super Boy 3, Super Bubble Bobble, Dr. Hello to SG-1000 & SG-1000 II emulation, It crashes & freezes on Genesis Plus GX. but fine works on PicoDrive. SG-1000 & SG-1000 II uses original TMS9918. I'm NOT Spamming

See:

**Super Boy I. (SG-1000) on Genesis Plus GX (SG-1000 & SG-1000 II emulation model)**
![Super Boy I (K)-220809-205658](https://user-images.githubusercontent.com/110823345/183744758-6f7c4a7d-f1bd-4bb3-8de4-ef27b6c3102f.png)
**Super Boy I. (SG-1000) on PicoDrive (SG-1000 emulation model)**
![Super Boy I (K)-220809-205717](https://user-images.githubusercontent.com/110823345/183744810-e55d79b1-734f-4c2f-8f53-b6ed815e00e4.png)
**Super Boy II. (SG-1000) on Genesis Plus GX (SG-1000 & SG-1000 II emulation model)**
![Super Boy II (K)-220809-205824](https://user-images.githubusercontent.com/110823345/183744841-a3f8cd20-71c7-4729-b903-003c5aaab5e2.png)
**Super Boy II. (SG-1000) on PicoDrive (SG-1000 emulation model)**
![Super Boy II (K)-220809-205838](https://user-images.githubusercontent.com/110823345/183744867-2a15ddfd-dc22-4ee4-b36e-f47dbf81518f.png)
**Super Boy 3 (SG-1000, Nemesis Mapper) on Genesis Plus GX (SG-1000 & SG-1000 II emulation model)**
![Super Boy 3 (K)-220809-205940](https://user-images.githubusercontent.com/110823345/183744892-fa7c8324-a8d6-4729-83ff-eefff34d60f7.png)
**Super Boy 3 (SG-1000, Nemesis Mapper) on PicoDrive (SG-1000 emulation model)**
![Super Boy 3 (K)-220809-210016](https://user-images.githubusercontent.com/110823345/183744914-83545520-38d5-4d94-bab1-99d14c9d8b4f.png)
**Dr. Hello (SG-1000) on Genesis Plus GX (SG-1000 & SG-1000 II emulation model)**
![Dr  HELLO (K)  ! -220809-210046](https://user-images.githubusercontent.com/110823345/183745359-f5f2e6f7-20da-41a6-933b-9d04a6c3189f.png)
![Dr  HELLO (K)  ! -220809-210059](https://user-images.githubusercontent.com/110823345/183745379-597506f5-1a36-469a-bb1d-c92b3f99f5ea.png)
![Dr  HELLO (K)  ! -220809-210106](https://user-images.githubusercontent.com/110823345/183745397-c35451ab-a24e-4225-9a3c-20434cf46c03.png)
**Dr. Hello (SG-1000) on PicoDrive (SG-1000 emulation model)**
![Dr  HELLO (K)  ! -220809-210127](https://user-images.githubusercontent.com/110823345/183745429-de7e490b-1577-4949-81ce-9fabcc7701e7.png)
![Dr  HELLO (K)  ! -220809-210134](https://user-images.githubusercontent.com/110823345/183745444-a3c62874-bf8f-4c22-bcdb-b87ccee58218.png)
![Dr  HELLO (K)  ! -220809-210147](https://user-images.githubusercontent.com/110823345/183745464-d3622e8f-6ff0-4675-bb68-fdef579302f0.png)
**Super Bubble Bobble (SG-1000) on Genesis Plus GX (SG-1000 & SG-1000 II emulation)**
![Super Bubble Bobble (K)-220809-211741](https://user-images.githubusercontent.com/110823345/183745668-024bdf11-5a14-45e2-a37c-835bcec140f7.png)
**Super Bobble Bobble (SG-1000) on PicoDrive (SG-1000 emulation model)**
![Super Bubble Bobble (K)-220809-211918](https://user-images.githubusercontent.com/110823345/183745689-423237a3-e3ad-4ca2-91fc-56da9166d1d8.png)

**Comment by ekeeke** [comment] 2022-08-09 19:53
Already explained #419, the issue is not lack of mapper emulation but lack of RAM in SG-1000 hardware. This will be addressed by #437.

**Closed by ekeeke** 2022-08-09 19:53 UTC
Labels: duplicate, invalid
