### ISSUE TITLE
Dungeon Explorer distorted sprite issues

### ISSUE THREAD

**Issue by jamosb** [ekeeke/Genesis-Plus-GX#40] opened 2015-01-19 00:24 UTC
When running Dungeon Explorer for Sega CD the sprites for monsters are garbled or missing. Any settings that I need to change to fix this or is it a known issue? 
I've gotten this with Windows and Android versions using Retroarch as the frontend.

I know its not the cue/bin as it runs fine with windows fusion 3.64

**Comment by ekeeke** [comment] 2015-01-19 08:00
It might be an emulation bug, I will check it when I have some time.

**Comment by ekeeke** [comment] 2015-01-20 09:21
I can confirm there is a bug with Dungeon Explorer USA release (happens as soon as other sprites than main character appear - happens in demo mode on title screen as well).

Strangely, the PAL release which I used for testing does not have this issue. Also there seems to be a PAL version floating around (.iso)  patched to work on US Sega CD and it work fine as well. Also, if you make a savestate on title screen with this patched version then rename the savestate to match the USA version CUE/BIN filename and load it within this version, it now works fine.

So it seems something got messed up during the game loading (before title screen) which later corrupt all moving sprites (main character sprite seems to disappear as well). Strange...

**Comment by jamosb** [comment] 2015-01-22 01:50
i will try the (E) version thanks!

**Comment by ekeeke** [comment] 2015-01-26 00:12
It should be fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/d11e0166face387321077fa5c3bdea83b52d01f6

For the record, the USA version of Dungeon Explorer accidentally tries to write PRG-RAM (on Sega CD size) from the Z80 (through 68k banked access), which corrupt data in RAM if those writes are allowed by the emulator. It would need some testings on real hardware to confirm it but it's very likely that writing from Z80 to PRG-RAM is not possible due to timing issues (this must go through MAIN-68k bus banking then SUB_68K bus banking).

**Closed by ekeeke** 2015-01-26 00:12 UTC
Labels: bug

**Comment by jamosb** [comment] 2015-01-26 03:15
So latest version of retroarch should have it or do they take a while to
update you core?

**Comment by ekeeke** [comment] 2015-01-26 09:13
There is no automatic or scheduled builds update and we are all people doing this on our free time so I have no idea how much it will take for retroarch core to be "officially" updated.

The purpose of a public repository though is that anyone could actually compile the updated core from here, for any platform, and use it with current version of retroarch. If you don't like to wait, learn how to compile it yourself, it's really not difficult.

**Comment by Oggom** [comment] 2015-01-26 20:46
Actually libretro has a buildbot now that provides daily builds for various platforms (including Windows):
http://buildbot.libretro.com/nightly/
The next official stable release is scheduled for this month.
