### ISSUE TITLE
G-Loc Game Gear is broken

### ISSUE THREAD

**Issue by davidj1987** [ekeeke/Genesis-Plus-GX#45] opened 2015-03-22 23:00 UTC
Tried it in 1.74 via Retroarch/Libretro, and it crashes after you complete a mission and are at the menu screen to buy weapons and fuel.

I tried downloading the latest .dll for the libretro version on the site here and it doesn't work with my retroarch install - am I doing something wrong? I select it and it won't open.

EDIT: Retroarch for x64-86 Windows.

**Comment by Oggom** [comment] 2015-03-22 23:38
I can confirm this happens in the latest nightly build too.

@davidj1987 Try using a nightly build of RA, the current stable one is outdated and should be avoided.

**Comment by ekeeke** [comment] 2015-03-24 23:01
Fixed in d2c03aadd949131cf4c743a33b695ee8efb704ca

Interestingly, this issue existed since the beginning but was never spotted before. It is caused by the game doing a dummy writes to port $18 which was wrongly interpreted as a write to memory control register (usually port $3E) and would accidentally disable the cartridge ROM. 

It would be interesting to know if this game runs fine on a Majesco Game Gear (which has a way to switch between cartridge ROM and internal boot ROM through memory control register).

**Closed by ekeeke** 2015-03-24 23:01 UTC
Labels: bug

**Comment by ekeeke** [comment] 2015-03-24 23:14
@davidj1987  .dll for the libretro version on this site is compiled for win32 so it will probably not work with x64 version of retroarch

**Comment by davidj1987** [comment] 2015-03-25 00:02
OK, I'll see if I can compile a version for Retropie. Thanks for looking into this!
