### ISSUE TITLE
Korean MSX Conversion games are bug/glitches on SG-1000 Emulation on Genesis Plus GX

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#430] opened 2022-05-14 13:02 UTC
Is it possible to fix bugs on Korean MSX Conversion on SG-1000 Emulation (Genesis Plus GX).

I found Korean MSX Conversion games:

- Super Boy I (Korea) (Zemina) (1989) (Unl)

- Super Boy II (Korea) (Zemina) (1989) (Unl)

- Super Boy 3 (Korea) (Zemina) (1990) (Unl)

But it's bug on SG-1000 Emulation on Genesis Plus GX Only. But it's fine on other SG-1000/SG-1000 II/Mark III/Master System/Master System II/Game Gear/Mega Drive/Genesis/CD emulator Including Kega Fusion, MEKA, SMS Plus GX, Gearsystem (Because uses 16KB RAM). Genesis Plus GX's SG-1000 Emulation Uses 1KB RAM.

It's not bug on Mark III/Master System/Master System II Emulation/Hardware On Genesis Plus GX but it's wrong colors.

See Bugs on SG-1000 Emulation on Genesis Plus GX:

Super Boy I (Korea) (Zemina) (1989) (Unl)
![157318414-47e36ade-a179-4d4e-a283-05fd36a63c6c](https://user-images.githubusercontent.com/105461925/168426478-19e640b6-d2c5-4bb4-b307-1c736fc22aaa.jpg)
Super Boy II (Korea) (Zemina) (1989) (Unl)
![157318708-4a391196-cf11-4a50-aa35-9179128295bd](https://user-images.githubusercontent.com/105461925/168426489-68094b63-dd8a-43fa-bba7-8ce8b76f53b7.jpg)
Super Boy 3 (Korea) (Zemina) (1990) (Unl)
![157318890-bd8a1ef8-0136-4510-885b-43036be104ea](https://user-images.githubusercontent.com/105461925/168426499-11534212-7e93-4128-a7c9-23d97efa1a3a.jpg)

Fixed:

Super Boy I (Korea) (Zemina) (1989) (Unl)
![157318446-537a3934-201d-4c59-80d9-e6c35fecf812](https://user-images.githubusercontent.com/105461925/168426558-d89354ff-b41b-470a-8076-a6583ab8abbf.jpg)
Super Boy II (Korea) (Zemina) (1989) (Unl)
![157318800-af477498-726d-49d6-8746-b16086e98f80](https://user-images.githubusercontent.com/105461925/168426585-5842bd13-4c39-42fa-8679-186101233835.jpg)
Super Boy 3 (Korea) (Zemina) (1990) (Unl)
![157318975-91784d1d-3c61-4e77-bc7f-8a26eff623d1](https://user-images.githubusercontent.com/105461925/168426617-aba13656-ac8f-49e8-b58a-c2198fffe84f.jpg)

**Comment by ekeeke** [comment] 2022-05-14 14:20
Stop it

Duplicate of https://github.com/ekeeke/Genesis-Plus-GX/issues/419 and the hundred same "issue" reports you posted with your alt accounts.

**Closed by ekeeke** 2022-05-14 14:20 UTC
Labels: duplicate, invalid

**Comment by MrKrabs07** [comment] 2022-05-15 08:37
@CraftFan24 stop spamming. @CraftFan24, You're fired for spamming on GitHub. With alt accounts. Your account should be terminated. Get back to work Mr. Squidward.

Send by Mr. Krabs

Rules:

No spamming

No p0rn

No DMCA (Copyright SpongeBob or more Copyrighted content)

No ass

No bitches
