### ISSUE TITLE
MD+ loop and volume issues

### ISSUE THREAD

**Issue by Relikk** [ekeeke/Genesis-Plus-GX#389] opened 2021-09-17 09:42 UTC
**Using Retroarch v1.9.1 on Windows 10 x64
Genesis GX Build 543e17f**

There are some issues with loops with the recent MD+ addition. Some tracks that are assigned to loop in the CUE file don't loop and some tracks that are assigned to not loop, will loop.

If the track does loop, the loop point isn't accurate. Here's a small video demonstrating a looped track in Xeno Crisis: https://youtu.be/WlariXJeEWM

You can hear the loop triggered in G+GX at around 7 or 8 seconds, it goes back to the beginning. In the second half of the video I demonstrate how the loop should sound and how it is triggered. MD+ uses CD sector values as loop points (you can see at 21 seconds I have the selection box changed to display "Absolute Frames" to input the loop value of 4115).

There's also a slight issue with CDDA volume. The MegaSD defaults CDDA audio to 80% in the options menu and seeing as it is the default that is what I would use to balance the CDDA audio against the in-game FX. The G+GX MD+ portion of the core sounds like it is maxed out to 100%, so the CDDA audio is a little on the loud side and drowns out the in-game FX a bit. May I suggest a 20% volume reduction for the MD+ portion of the core, or perhaps a volume slider defaulted to 80%?

Thanks, by the way, for the MD+ addition and for the recent fade fix. It's very much appreciated that we can have a good emulator for MD+ hacks now.

**Comment by ekeeke** [comment] 2021-09-17 10:56
The loop issue should have been fixed by this commit: https://github.com/ekeeke/Genesis-Plus-GX/commit/0c63be93f784170280318721fa21cb69aeaf5626
There was an issue with CUE file parsing where the LOOP command were being applied to the next track.

Regarding the CDDA volume, it is indeed not adjusted and corresponds to default PCM volume in WAV file, BIN file  etc... Adding configurable volume for CDDA stream should probably be handled with a core setting as it could benefit to CD games and Mode-1 hacks as well.

**Comment by Relikk** [comment] 2021-09-17 11:24
Ah, yes. Sorry. I did not see that commit.

The loops are triggering at the correct points now, but there is one minor issue I'm hearing and it's that they're not a smooth transition. There's a very, very slight delay/hiccup. I know the MegaSD uses a two sector buffer to compensate for something like this and to make it a seamless transition.

**Comment by ekeeke** [comment] 2021-09-17 11:38
A software emulator works differently since audio can be read without delay from input file and file seeking is also close to immediate.

I think I now though why it's not as smooth as real hardware: the emulator updates audio samples once per frame,  which correspond to a certain amount of CDDA samples (around 735 samples at 60 fps) and the loop point (end of current track) is only checked afterall these samples have been updated so it's possible (and very likely) that a few samples are rendered pas the end of the track before the loop occurs. I will have a look if this can be fixed (it probably requires to check for track end after each sample, which could be quite CPU intensive)

**Comment by Relikk** [comment] 2021-09-17 14:20
Another small bug with volume that I've noticed, if you try Darius II in particular, after you clear a stage the volume of the "Round Clear" audio file is substantially reduced, and every subsequent occurence of this gets further reduced.

**Comment by ekeeke** [comment] 2021-09-18 13:25
> Another small bug with volume that I've noticed, if you try Darius II in particular, after you clear a stage the volume of the "Round Clear" audio file is substantially reduced, and every subsequent occurence of this gets further reduced.

This one was another mismanaged edge case: the initial cdda volume was not properly restored if an immediate pause command was sent while fade-out is still in progress. This one was fixed (along with some other possible edge cases) by https://github.com/ekeeke/Genesis-Plus-GX/commit/9863375a5ae125d6f23a1611d64a5f7b4e15d0d3

**Comment by ekeeke** [comment] 2021-09-26 14:41
@Relikk 
> The loops are triggering at the correct points now, but there is one minor issue I'm hearing and it's that they're not a smooth transition. There's a very, very slight delay/hiccup. I know the MegaSD uses a two sector buffer to compensate for something like this and to make it a seamless transition.

Can you give an example of a MD+ patched game and track were this is noticeable ? I have modified CDDA playback for when MegaSD CD overlay is emulated so that the loop points are sample-accurate but I am not sure if this works as I could not rally notice the non-smooth transition before.

Alternatively, if you have Retroarch 32-bit version for windows, you can try this test version and tell me if loops are smoother with it.

[genesis_plus_gx_libretro_megasd_test1.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/7231583/genesis_plus_gx_libretro_megasd_test1.zip)

**Comment by Relikk** [comment] 2021-09-26 15:42
The 32-bit version you linked is the same for me as the 64-bit version.

I've tested the character select theme of Street Fighter II' Special Champion Edition in particular when I've tested the loop transitions. It's track 02 in the sound test in the options menu. It's just not quite right. There are more, but I'll use this one as an example in the video, along with another issue. Sometimes when starting a game there is slight distortion or noise. The Capcom logo theme in the video, along with the silence demonstrates it. Restarting the core sorts it out.

https://youtu.be/g1pIUbNzZZ8

Around 24 seconds is the loop trigger point. It's not as accurate as the audio editor at 47-48 seconds.

Another issue I've noticed is on some games when a level or a screen transition with a track change occurs there is a stutter. The track will trigger and then freeze the game and mute the audio, then unfreeze and continue. I used Darius II as an example in the video below.

https://youtu.be/SVbE3RTH1bo

**Comment by ekeeke** [comment] 2021-09-26 20:06
>Around 24 seconds is the loop trigger point. It's not as accurate as the audio editor at 47-48 seconds.

Honestly, I have carefully listened to these two parts at least ten times in a row but I hardly notice any differences between them. The transition at 0:24 sounds just as smooth and natural to me.

Anyway, now that audio loopback is implemented at sample granularity (in the 32 bit build linked a few posts above), the only possible cause I see for a difference would be different loopback triggering point: in Genesis Plus GX, I wait until the last sample of the WAV file before playing back from the start (with offset) but maybe MegaSD is looping back a few sectors before the end of the track ?

>The track will trigger and then freeze the game and mute the audio, then unfreeze and continue.

This is really weird and I am pretty sure this did not happen with my SDL/Win32 build when I tested this game. Maybe this is something caused by Retroarch specific file i/o functions or slow device access when seeking filed , I don't know but there is nothing in my implementation that would cause the emulator to freeze like that...

**Comment by Relikk** [comment] 2021-09-26 21:33
I know it's kind of hard to hear to the untrained ear (sorry, I'm a sound engineer by trade so these things are very noticeable to me), and it has been worse than that at times. The recording I got there was one of the best ones I've heard. I'll try and get something a bit more noticeable in the next few days as I didn't have much time to capture more than what's on display, currently, but it is definitely not an accurate loop at the very least.

The access times could be an issue, for sure. It doesn't tend to happen if the folder for the game is on an SSD. I have all my games on a mechanical drive and that example was recorded with the game from that drive. In saying that, as a comparison I have all my MSU1 games on the same drive and have no such problems with those on supported emulators.

**Comment by Relikk** [comment] 2021-09-28 08:51
That did the trick. Loops are perfect now. Thank you.

All that remains is the volume adjustment.

**Comment by ekeeke** [comment] 2021-09-28 18:30
> That did the trick. Loops are perfect now. Thank you.

Great. I commited the fixes in https://github.com/ekeeke/Genesis-Plus-GX/commit/3cf83e7557a7869fbe312ca059355d2cc76058e6

**Comment by ekeeke** [comment] 2021-10-07 21:23
> All that remains is the volume adjustment.

Configurable CD-DA & PCM outputs mixing volumes added in https://github.com/ekeeke/Genesis-Plus-GX/commit/9254c331d2ac1cf861acc781599722a527a7d2ad

**Closed by ekeeke** 2021-10-07 21:23 UTC
Labels: bug, enhancement, core/MD, core/CD
