### ISSUE TITLE
Corrupted .PNG files. Snaps and Savestates. 

### ISSUE THREAD

**Issue by Kingharthacnut** [ekeeke/Genesis-Plus-GX#515] opened 2023-07-15 22:16 UTC
The .png files that are taken as a Snaps and Savestate cover images have lines of data corruption on them! Is this a GPU problem on my end, is my Wii dying? If you need further info let me know - i'll test other games tommorrow.

![Sonic3C](https://github.com/ekeeke/Genesis-Plus-GX/assets/91091384/cfb5e142-3689-4e14-8859-8ffd0d592e63)
![IMG_20230715_225755](https://github.com/ekeeke/Genesis-Plus-GX/assets/91091384/f1e65683-32b1-4d24-b952-222aa68e0e6a)

**Comment by ekeeke** [comment] 2023-07-16 11:49
Your Wii is not dying, otherwise it would also happen while playing any game (emulated or not) ;-)

Yes, I noticed long time ago that pixels eventually got corrupted when saving screen to PNG file but it does not happen all the time so retaking another screenshot (or saving over a savestate) would fix it. Back then, I always thought it was some timing issue in my code or bug in libogc functions (I use a GPU hardware feature that copy internal framebuffer to a texture in CPU memory then write this texture to PNG file) but never found out the root cause.

However, looking at my 10 years old code again now, I think I found some potential cache issue that could lead the CPU to
 read corrupted data from memory when writing the PNG file. Could you give a try to attached test dol and see if it fixes that issue ?

[genplus-gx-test-20230716.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/12063916/genplus-gx-test-20230716.zip)

**Comment by Kingharthacnut** [comment] 2023-07-18 20:28
I used the new .dol and it does not show any corruption - I did multiple save states and checked the background .png and saw nothing out of place. The Shots .png was also fine when checked on my main computer - I could only check one though as the Shots folder only holds one .png per game. 

Thank you.

**Comment by ekeeke** [comment] 2023-07-19 14:37
Thanks for testing. I will commit the fix later but this confirms these changes fixed this long standing issue.

**Comment by ekeeke** [comment] 2023-07-24 21:20
Now officially fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/a8d61b039189225bf8ab8438a38f758b8868198a

**Closed by ekeeke** 2023-07-24 21:20 UTC
Labels: bug, gamecube, wii
