### ISSUE TITLE
Black screen Landstalker (Spanish translation with expanded rom)

### ISSUE THREAD

**Issue by John3d** [ekeeke/Genesis-Plus-GX#337] opened 2020-10-22 17:20 UTC
Hi

Would it be possible to run this game in the emulator?
The game starts but after selecting the game, the screen goes black.
This translation requires expanding rom size, maybe that's why it doesn't work.

https://www.romhacking.net/translations/3377/

**Comment by ekeeke** [comment] 2020-10-31 13:30
Yes, this ROM hack expects SRAM and ROM data to be accessible at the same time from the same memory area (upper 2MB cartridge area) but the emulator only enables ROM by default when SRAM is mapped within ROM area and expects the game to enable SRAM / disable ROM when needed using bankswitching mechanism, because this is what all official games are doing.

I added an exception in https://github.com/ekeeke/Genesis-Plus-GX/commit/298b09fcd18df7f0fb1aee50981ab910a0597ff9 for this particular game and now force SRAM to be enable for this game even if ROM size is larger than SRAM start address, which fixes the back screen on startup with the Spanish translation.

Updated libretro build (win32 only though) is available from here https://github.com/ekeeke/Genesis-Plus-GX/blob/master/builds/genesis_plus_gx_libretro.dll until this got merged in libretro fork repository.

**Closed by ekeeke** 2020-10-31 13:30 UTC
Labels: bug, core/MD

**Comment by John3d** [comment] 2020-10-31 19:55
Sorry ekeeke but I have tried this core updated in retroarch (32 bits) and it follows the same error.
The game starts as I said in the first message, but after this screen it crashes and the screen is black.

![Landstalker - The Treasures of King Nole (Spain)-201031-205213](https://user-images.githubusercontent.com/21139065/97788682-044e3280-1bbb-11eb-8c62-daa0a570e472.png)

**Comment by ekeeke** [comment] 2020-11-01 00:29
Indeed, it only works if you already have a properly initialized SRAM file for the game (which I had, hence why it worked when I tested).

After looking a little bit more into this issue, it appears to be caused by a bug in the patch: it actually enables (resp. disables) SRAM using official SRAM/ROM switching mapper before (resp. after) accessing SRAM but when enabling SRAM, it incorrectly sets the SRAM write protect bit, which prevents SRAM from being written. Depending on the initial SRAM state (usually restored from associated .srm file if it exists or set to some default value like 0x00 or 0xff), in flashcarts or emulators that correctly emulate this bit behavior, this either causes a crash (when SRAM is set to 0xff for example) when starting a new game because unexpected SRAM read-back values make the code to do crazy things or the game starts normally (when SRAM is already initialized or set to 0x00 for example) but with in-game saves not working properly.

I have attached a fixed IPS file that you can use on the expanded ROM file and reverted my latest commit as it was not the proper fix.
[landstalker-es-v2.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/5470021/landstalker-es-v2.zip)

**Comment by John3d** [comment] 2020-11-01 11:32
Thanks ekeeke, I have tested the patch and it works perfectly.
I will contact the author of the translation to update the patch in romhacking.
Thanks again and sorry for the inconvenience.
