### ISSUE TITLE
SMS games Bart vs. the Space Mutants & Operation Wolf crash in NTSC

### ISSUE THREAD

**Issue by ghost** [ekeeke/Genesis-Plus-GX#273] opened 2019-05-09 04:47 UTC
Please Change the Region Code for those 2 Games to Pal Emulation.

Evidence of Bart vs. the Space Mutant Crashing in NTSC.
[Crashing Evidence.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/3160415/Crashing.Evidence.zip)
[Crashing Evidence 2.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/3160435/Crashing.Evidence.2.zip)

Bart vs. the Space Mutants (Master System) & Operation Wolf (Master System) needs to be Labeled as Unplayable in NTSC (Almost as Unplayable as Home Alone (Master System) in NTSC).

**Comment by ekeeke** [comment] 2019-05-09 05:36
Thanks for the video capture. Is is a capture from real NTSC hardware or from emulator ? This  game apparently had a release in Brazil so it should work at 60hz normally (region code has no impact in SMS games only VDP 50hz/60hz setting) so I need to confirm it happens on real hardware and isn't emulation bug. Does it happens the same in other emulators (Fusion, Meka, Emulicious) ?

Same for Operation Wolf (where does it crash exactly ?)

**Comment by ekeeke** [comment] 2019-05-09 13:56
OK, it seems to be confirmed that these 2 games are buggy on NTSC hardware:

- Bart vs The Space mutants: http://www.smspower.org/forums/12436-BartVsSpaceMutantsPAL#61815
- Operation Wolf: http://www.smspower.org/forums/12455-OperationWolf#62095

Both are also listed as 50hz only in Meka's database (https://github.com/ocornut/meka/blob/master/meka/meka.nam)

Still not 100% sure if the reason is really a 50Hz/60Hz timing issue (emulators are simply forcing 50hz video mode for such problematic games) since those games were also released in Brazil (where consoles runs at 60hz) and, looking at those SMS Power threads, it seems some people reported they were working fine in emulators set to NTSC (which ones ?) or on Genesis hardware with Power Base Converter...

**Comment by funbars** [comment] 2019-05-09 15:06
Operation Wolf is Europe, Australia, Brazil. Maybe Brazil (PAL-M) machine uses slightly changed timing? It's not exactly NTSC-60 but near.

Or have to rip apart and compare region carts.

**Comment by ekeeke** [comment] 2019-05-09 15:47
No, PAL-M is just a video signal encoding format, it does not change CPU or VDP timings compared to NTSC. Even if it used a slightly different master clock speed, it would not matter for game engine as all clocks are derived from master clock so it would be transparent. The only thing that matters is the number of CPU cycles per line (fixed to same value in 50hz and 60hz mode) and number of lines per frame (262 in 60hz mode vs 313 in 50hz mode) between two frame interrupts.

**Comment by funbars** [comment] 2019-05-17 02:45
Any clues from articles?

http://www.smspower.org/forums/download.php?id=2408&sid=c1eb1f82472c45f0c6be97903ba50de8
```
Operation Wolf
----------
Crashes and resets on NTSC SMS 1 models with Snail Game built-in. Status with
other models unknown. Will work with a Power Base Converter (CRV, ifkz).
```

https://raelcunha.com/2016/07/29/my-retro-journey-sega-master-system/
```
Brazilian SMS I and II (which are the “Power Base” models) are the only ones with the 3D glasses input.

Sega 315-5124 in Brazilian SMS I and II, the “Power Base” ones

Get a SMS model I or II if you want to play in old TVs and use 3D glasses and the gun (Light Phaser).
```

http://www.smspower.org/forums/1561-3155246VDPVs3155124VDP
```
315-5124 ("SMS 1" VDP) and 315-5246 ("SMS 2" VDP/PSG)

I'm emulating both types in SMS Plus, as well as the Mega Drive's implementation of the SMS VDP which is a bit different from the other two.

my note: Some games work on 5124 but not 5246. And other way.
```

**Comment by ekeeke** [comment] 2019-05-17 12:38
>Any clues from articles?

Not really, the differences between VDP models are known and emulated, also "SMS 2" VDP is used by default in the emulator (for NTSC or PAL) so I am quite sure it has anything to do with this issue (also I know for sure Operation Wolf works fine on PAL Master System 1st model).

Anyway, the fact that those games work fine in emulator if you set the region to PAL  and the only thing that changes in this case for software is the the number of lines/cycles between two frame interrupts seems to indicate the issue is only related to 50/60hz VDP setting.

 I don't know, maybe those games were buggy just the same in Brazil and nobody ever cared or reported it: there does not seem to be any confirmation that these games work without glitches on Brazilian consoles and the reports that some of them work Genesis consoles with PBC are quite vague.

**Comment by funbars** [comment] 2019-05-17 13:00
> I don't know, maybe those games were buggy just the same in Brazil and nobody ever cared or reported it: there does not seem to be any confirmation that these games work without glitches on Brazilian consoles and the reports that some of them work Genesis consoles with PBC are quite vague.

Good point.

Maybe we'll see ntsc hack patches for both games someday.

**Comment by ekeeke** [comment] 2019-05-28 22:15
I can't reproduce crash in these games with emulator so it probably is related to very tight VDP timings that 
are not emulated and therefore it does not make much sense forcing them to 50hz for the moment.

**Closed by ekeeke** 2019-05-28 22:15 UTC
