### ISSUE TITLE
Marko's Magic Football (Mega CD) Graphic Bug

### ISSUE THREAD

**Issue by KamiLordus** [ekeeke/Genesis-Plus-GX#482] opened 2023-01-30 15:02 UTC
On one of the first screens (location map) there is a graphic error - the bottom of the screen.
Please fix it.

![215456644-1fb76b3e-a99c-4b44-bb0f-340eec470f23](https://user-images.githubusercontent.com/123302593/215513463-120ca030-b75c-469c-8ea7-3a7a30c54ba2.png)

Issue originally reported in:
https://github.com/libretro/Genesis-Plus-GX/issues/318

**Comment by ekeeke** [comment] 2023-01-30 20:11
Sorry, I meant this one should be kept open and the ones in libretro repository closed as it is easier for me to keep track of core issues here (and I doubt anyone else is going to look into this anyway).

As I indicated in libretro repository, this is caused by sub-cpu trying to write into word-ram while it is allocated to main-cpu (RET bit set in 2M mode). On real hardware, sub-cpu is halted, which delays the write after word-ram is being read through VDP DMA so there is no graphics corruption. This is not emulated by this emulator (and apparently neither by most software emulators as this bug also occurs In Kega Fusion, Gens, Picodrive,...) and will require some changes to both Mega-CD hardware and 68k cpu core emulation, as current core (MAME's Musashi) does not permit to halt cpu in the middle of an instruction (and postpone read or write memory access until cpu is not halted anymore).

**Comment by KamiLordus** [comment] 2023-01-30 22:06
Thank you for your clarification and interest in reporting the issue.
However, it looks very complicated and probably impossible to fix.

**Comment by ekeeke** [comment] 2023-11-18 18:39
Fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/6cc8bbc2776dfbe62411fc1e8fbc5807c8e3558d

**Closed by ekeeke** 2023-11-18 18:39 UTC
Labels: bug, core/CD
