### ISSUE TITLE
Shining Force CD (PAL): noise instead of music in Windows build of libretro core

### ISSUE THREAD

**Issue by nE0sIghT** [ekeeke/Genesis-Plus-GX#288] opened 2019-09-01 17:45 UTC
Hello.

I'm using latest Genesis Plus GX libretro core in x86_64 Windows 10 with RetroArch 1.7.8 and getting noise instead of some music in Shining Force CD. E.g. there is noise in game menu and in 1st game scene (when bad guys making bad things). However other music plays fine. This noice is something like "white noise".

However in my Gentoo box with self compilled libretro core I have no issues with same CD image.

Also there is no issues with picodrive core on same Windows box sith same CD image.

**Comment by ekeeke** [comment] 2019-09-01 18:51
If it works with one version of Retroarch and not another, this is hardly a core issue but rather some regression in Retroarch, a problem with your Retroarch configuration or a so I don't see what I can do to help you (I'm maintaining the multi-platform emulation code but I am not responsible for the libretro port or frontend code).

Some things that can help figuring where that issues come from:
- give more details about the CD image (cue+single bin, multiple bins, iso+wav, chd ?) and try with another one
- check if missing music is supposed to be one of the CD audio tracks, PCM (from Mega CD hardware) music or FM (from Mega Drive hardware) music
- check if all audio tracks are playing fine in boot CD player and none are missing (press A to enter it instead of starting the game)
- reset core settings to default

**Comment by nE0sIghT** [comment] 2019-09-01 19:55
> give more details about the CD image (cue+single bin, multiple bins, iso+wav, chd ?) and try with another one

It's a cue + iso + multiple wav tracks

> check if missing music is supposed to be one of the CD audio tracks, PCM (from Mega CD hardware) music or FM (from Mega Drive hardware) music

"Noise" tracks are CD audio tracks.

> check if all audio tracks are playing fine in boot CD player and none are missing (press A to enter it instead of starting the game)

I just checked multiple times - in boot CD player some CD tracks became "noise" sound. The strange thing is that "broken" tracks are random between game reboots - most of them are played well, but some became noise.
I also was wrong thinking some constant tracks are broken - in game tracks broken randomly also as in boot CD player,

> reset core settings to default

Unfortunately, it doesn't help.

**Comment by ekeeke** [comment] 2019-09-01 20:15
Looks like a regression or instabilities within CD image file reading code on retroarch/libretro side. I know this was modified by libretro (still not backported in this repository though) to add real cdrom support (on windows I think) so maybe some bugs were introduced. You should try with different game using same iso/wav format and with a different image format for that game to see if this is specific to that game or that CD image format type, as it could help narrowing the root cause of your issue.

Anyway, I am closing this for now as I can not reproduce it on my side (and Mega CD emulation code has not been changed for monhs so they are hardly any regression introduced on core side) and you will have to report this to libretro devs.

.

**Closed by ekeeke** 2019-09-01 20:15 UTC
Labels: invalid
