### ISSUE TITLE
Inaccurate Behavior in MCD Sub CPU Bus Request 

### ISSUE THREAD

**Issue by OrionNavattan** [ekeeke/Genesis-Plus-GX#520] opened 2023-08-08 20:58 UTC
Developing my [experimental error handler](https://github.com/OrionNavattan/MegaCDErrorHandler) revealed an inaccuracy in the sub CPU bus request mechanism, and specifically in how it is handled if the sub CPU has been stopped using the `stop` instruction. 

I can't find any information about it in the 68000 user and programmer manuals, but what I've observed, it appears that the 68k does not respond to bus requests if the `stop` instruction has been used to halt it. On real hardware (tested with Genesis Model 1 VA2 + Sega CD Sony Model 2), if a stop instruction is executed on sub CPU, immediately followed by the main CPU requesting the bus, the request will never be granted, leading to an infinite loop if the main CPU is waiting for acknowledgement. GPGX, however, in both the libretro and OpenEmu versions, allows the request to complete as if the sub CPU were still running normally.

**Comment by OrionNavattan** [comment] 2023-08-08 21:07
A small test ROM I put together that demonstrates this issue: https://drive.google.com/file/d/1cTOo-_PwBF8Mbei_ZzvOitNoGLKzskPY/view

On real hardware, this ROM hangs on a black screen. In GPGX, it (incorrectly) shows an error handler screen due to the issue I described.

**Comment by ekeeke** [comment] 2023-08-09 08:03
Yes, sub-cpu bus request acknowledge is not really emulated as no games rely on this and the timing would be to hard to emulate precisely anyway so $A12001 bit 1 always returns 1 by default as soon as it is set by main-cpu.

It is weird though that 68000 cpu would be stopped state would not respond to bus requests, this is indeed not documented anywhere (68000 user manual only says that when cpu is halted - though /HALT pin - bus arbitration signals behave as usual) and I doubt any software emulator implement this behavior. This would also mean that z80 should not be able to access main-cpu bus while it is stopped, which is kinda limiting (this can easily be verified by another test rom I guess).

Or maybe this is only something with that bit on mega-cd gate array side in a particular case, I will have to check what that test ROM is actually doing I guess. Does it behave correctly in other emulators that have Mode 1 support (Kega Fusion, Blastem and Ares I think) ?

**Comment by OrionNavattan** [comment] 2023-08-09 18:55
>This would also mean that z80 should not be able to access main-cpu bus while it is stopped, which is kinda limiting (this >can easily be verified by another test rom I guess).

The Z80 uses cycle stealing to read from ROM, which I don't think involves requesting the bus at all. A quick test involving replacing the entire WaitForVBlank routine in a Sonic 2 disassembly with a `stop #$2300` had no audible effect on my Model 1 VA2; DAC samples continued to be read from ROM correctly. GPGX, Blastem, and Exodus all behaved as hardware.


>I will have to check what that test ROM is actually doing I guess. 

I've attached the source of the test ROM below for your convienence. It's basically identical to [this](https://github.com/OrionNavattan/Mega-CD-Error-Handler-Test), except for adding an illegal instruction to crash the sub CPU, and trapping the sub CPU with a stop instruction instead of an infinite loop. The relevant parts are in the two exception handler files as follows:

```
; Sub CPU's error handler
; dumps the registers and signals the main CPU that we've crashed
ErrorHandler:
		move	#$2700,sr				; disable all interrupts
		st.b (mcd_sub_flag).w		; set flag to let main CPU know we've crashed (assumes communication protocol includes checking this flag for $FF before sending commands or while waiting for responses)
		movem.l	d0-a6,-(sp)				; dump all registers
		move.l	usp,a0
		move.l	a0,-(sp)			; dump USP (unnecessary if BIOS is being used, as user mode can not be used with it)	
	.waitmain:
		cmpi.b	#$FF,(mcd_main_flag).w	; has the main CPU noticed?
		bne.s	.waitmain	; if not, branch
		; Main CPU has noticed
		move.l	sp,(mcd_subcom_0).w	; get address of bottom of stack (including dumped registers) for main CPU
		clr.b	(mcd_sub_flag).w ; clear flag to let main CPU know we are done
		;bra.s	*	; stay here forever (the correct way to do this)
		stop #$2700	; this does not work, as it prevents the sub CPU from responding to the main CPU's bus request!

```

```
; Main CPU's handler for sub CPU errors
; (entered via trap #0 if $FF is found in mcd_main_flag)
SubCPUError:
		disable_ints				; disable interrupts
		move.b	(mcd_sub_flag).l,(mcd_main_flag).l	; let sub CPU know we've noticed

	.waitsub:
		tst.b	(mcd_sub_flag).l	; is the sub CPU done?
		beq.s	.waitsub			; if not, branch	
		
	.waitsubbus:	
		; If sub CPU has been stopped using the stop instruction, this becomes an infinite
		; loop, as the sub CPU will never acknowledge the request.
		bset	#sub_bus_request_bit,(mcd_reset).l			; request the sub CPU bus
		beq.s	.waitsubbus					; if it has not been granted, wait		
```

Checking a couple of other platforms: on Blastem Nightly, the ROM causes the entire program to hang, while the Mega Everdrive's FPGA exhibits the exact same incorrect behavior as GPGX (the bus request is granted).

[Mega-CD-Error-Handler-Test (GPGX Bug).zip](https://github.com/ekeeke/Genesis-Plus-GX/files/12305723/Mega-CD-Error-Handler-Test.GPGX.Bug.zip)

**Comment by ekeeke** [comment] 2023-08-09 19:12
>The Z80 uses cycle stealing to read from ROM, which I don't think involves requesting the bus at all
No, 68k bus access is requested on every Z80 cpu access (by bus arbiter) and 68k execution is suspended. That is the reason why

**Comment by ekeeke** [comment] 2023-08-09 22:05
`.waitsub:
		tst.b	(mcd_sub_flag).l	; is the sub CPU done?
		beq.s	.waitsub`

Unless I am missing something, I think this wait loop is incorrect (should be 'bne' instead of 'beq').

Indeed, mcd_sub_flag is set to 0xff (by sub-cpu) when entering main-cpu handler so you want to loop until is cleared by sub-cpu (after stack address has been written to comm register) but here you are waiting for it to be different from 0 ('beq' branches if tested value is zero). On real hardware, with the two cpus operating in parralel, what probably happens is that sub-cpu is fast enough to clear the flag before it is being tested by main-cpu so you get stuck in an infinite loop (but not the loop you initially thought). In software emulators, parralel processing is not possible so main-cpu and sub-cpu need to be run for a few cycles one after another, with the amount of cycles having a significant impact on emulator processing speed (the more you switch between CPUs during emulated timeframe, the less optimized is your emulator). In GPGX, granularity of synchronization between main-cpu and sub-cpu is not as fine as in Blastem, so most likely, the 'tst' instruction from main cpu is processed before sub-cpu timeslot is processed so main-cpu handlers immediately exits the 'waiting' loop and continue its execution.

**Comment by OrionNavattan** [comment] 2023-08-11 03:30
Gah, you're right, that branch should be a bne. Sheer luck that it did not cause any problems. Thank you for pointing that out; it's been fixed.

However, that bug does not appear to be related to the issue I described in my initial post. That still occurs even with this bug fixed. (To be clear, the hang on real hardware only occurs if the sub CPU is halted with stop rather than an infinite loop; this still happens even with the branch condition bug fixed.)

**Comment by ekeeke** [comment] 2023-08-11 07:07
Damn, that's really weird
Could you please upload the corrected test ROM (with branch condition fixed and stop instruction kept) so I can check it when I have some time ?
Also, could you verify if that new test ROM behaves as real hardware (main-cpu hang) in Blastem ? As indicated above, looking at the sourcecode, this emulator does not care about sub-cpu stopped status and will always return 1 in that bit once set by main-cpu (like GPGX) so if it still hangs as real hardware, this means the cause is something else.

**Comment by OrionNavattan** [comment] 2023-08-12 02:36
Here you go. I checked, and there is no change of behavior on any platform: GPGX and Mega EverDrive Pro FPGA grant the bus request, Blastem locks up, and real hardware hangs on black screen.

[MCD Error Handler Test (Stop Ins).zip](https://github.com/ekeeke/Genesis-Plus-GX/files/12326259/MCD.Error.Handler.Test.Stop.Ins.zip)

**Comment by birdybro** [comment] 2023-08-12 20:46
Can't seem to test it on MiSTer FPGA MegaCD core, the "Press Start" upon BIOS doesn't load at all.

**Comment by ekeeke** [comment] 2023-08-13 12:15
@birdybro : the .bin file is a Genesis ROM file that uses Sega CD Mode 1, not a CD image binary. It does not require a CD file, it just uses Sega CD hardware (by decompressing Sub-CPU program into Sega CD RAM) but, in Mister, you probably need to create a CUE file in same directory with some random audio tracks to enable Sega CD Mode 1. Note that Genesis Plus GX automatically enables Sega CD mode 1 when it detects a specific field in ROM header ('C' in supported peripherals field), without the need of a CUE file.

**Comment by ekeeke** [comment] 2023-08-13 15:35
>Blastem locks up

I just tested the ROM file you uploaded in Blastem debugguer and it seems the emulator indeed completely freezes (does not respond to inputs anymore) as soon as the stop instruction is executed on sub-cpu side (if I switch debugger to main-cpu side and do step by step, it freezes while main-cpu waits for sub-cpu to clear the communication flag). Maybe it is related to the fact it is executed during illegal exception processing, I don't know ? It might be interesting to report this to @MaskOfDestiny so he could have a look as t. On real hardware, maybe it is not just the stopped state but the combination of stopped and some exception processing state which puts the cpu in some undocumented state where bus requests are ignored, who knows ?

**Comment by birdybro** [comment] 2023-08-13 20:30
> @birdybro : the .bin file is a Genesis ROM file that uses Sega CD Mode 1, not a CD image binary. It does not require a CD image file, it only makes use of Sega CD hardware (by decompressing Sub-CPU program into Sega CD RAM) but, in Mister, you probably need to create a CUE file in same directory with some random audio tracks to enable Sega CD Mode 1. Note that Genesis Plus GX automatically enables Sega CD mode 1 when it detects a specific field in ROM header ('C' in supported peripherals field), without the need of a CUE file.

Ah I see. Yeah we just need the cartridge rom named `cart.rom` in the same folder as the cue/bin (or chd) and it should load the cart. I'm just gonna through an MSU-MD cue/bin in there and do it like this:

![image](https://github.com/ekeeke/Genesis-Plus-GX/assets/16388068/bf5f10ca-95d4-4e8a-8412-81470937a223)

Testing now and this is the result:

![Screenshot 2023-08-13 14-29-46](https://github.com/ekeeke/Genesis-Plus-GX/assets/16388068/0391c8ff-6eaa-49ce-b1e6-496e08ca2598)

**Comment by ekeeke** [comment] 2023-08-13 21:28
Well, looking at Mister implementation (ASIC.vhd), setting SBRK bit in register A12000 does not really request sub-cpu bus (read hardware would set S68K /BR pin low) but instead halts the sub-cpu (through S68K /HALT pin) and reading back the register simply returns the set value of SBRK bit (like in GPGX) instead of returning sub-cpu bus access status (real hardware would return 1 only when sub-cpu bus becomes available i.e S68K /BG pin is low and both /BGACK and /AS pins are high). 

So, unfotyunately, it cannot be used to check behavior of FX68K core when 68K bus is requested while cpu is stopped...

Thanks anyway

**Comment by OrionNavattan** [comment] 2023-08-13 22:02
> I just tested the ROM file you uploaded in Blastem debugguer and it seems the emulator indeed completely freezes (does not respond to inputs anymore) as soon as the stop instruction is executed on sub-cpu side (if I switch debugger to main-cpu side and do step by step, it freezes while main-cpu waits for sub-cpu to clear the communication flag). Maybe it is related to the fact it is executed during illegal exception processing, I don't know ? It might be interesting to report this to @MaskofDestiny so he could have a look at it. On real hardware, maybe it is not just the stopped state but the combination of stopped and exception processing state which puts the cpu in some undocumented state where bus requests are ignored, who knows ?

That's definitely a bug if the stop instruction is freezing the emulator. I'll report it in the RetroDev Discord.

And funnily enough, I read this just as I finished an update to the test ROM that all but confirms what I suspected was happening on real hardware. I added a feature that counts down while waiting for the bus request to complete, triggering a custom error message via trap 1 if it times out, and that message is being triggered.
[MCD Sub Stop Ins Test.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/12330508/MCD.Sub.Stop.Ins.Test.zip)

**Comment by ekeeke** [comment] 2023-08-15 09:32
Well, I guess that settles it then, thanks for your tests.

It's surprising that this is not documented anywhere though (I tried to look in Jorge Cwik FX68K core and in recent Nuked verilog core, both implemented from 68000 die analysis, but could not really find what the STOP instruction exactly does and what is its impact on signals used by bus arbitration).

Not sure either what are exact conditons or logic used by Mega-CD gate array to return 1 in SBRQ bit. 

Since you have real Mega-CD hardware, could you please do the same test as in this last test ROM but with bit 0 (SRES) and bit 1 (SBRQ) set to different values successively, namely 00b (sub-cpu in reset state, no bus request), 01b (sub-cpu in reset state, bus requested) and 11b (sub-cpu running after reset, bus requested), then check SBRQ bit returned value. It would also be interesting to test these values with sub-cpu not being stopped (at least the two first values, to see if bus appears as available when sub-cpu is in reset state). Note that you will need to modify the BSET/BEQ sequence to do this (and use MOVE.B/BTST/BEQ instead), which is also the way the bits should be set in this register according to Mega-CD hardware manual (it explicitely states BSET should not be used but I am not sure why, maybe because setting the other bit with its read value is not safe)

**Comment by OrionNavattan** [comment] 2023-08-15 22:54
>it explicitely states BSET should not be used but I am not sure why
I think it's safe to say that's yet another instance of incorrect information in the development manuals, given that those BSET/BEQ and BCLR/BNE sequences are practically taken verbatim from the North American Model 2 BIOS. In fact, a quick check in a hex editor confirms that at least the latter is used in every known BIOS bootrom, so it begs the question where the hell that incorrect statement came from.


Anyhow, made six test roms this time around, testing each of those conditions with the bus request and reset bits, one with sub CPU stopped, and one with it trapped in an infinite loop. They're not very sophisicated, simply showing a green screen if the bus request succeeds, and a timeout error if the request fails. In all three cases, the bus request fails if the sub CPU is halted with a stop instruction. If the sub CPU is running, it appears that the status of reset does not matter, the bus request will succeed even if the sub CPU is in the reset state (the NA Model 2 BIOS in fact relies on this behavior, and I suspect all the other BIOS do so too).

More curious, however, is the fact that simply resetting the sub CPU without requesting the bus appears to nevertheless trigger a bus request. Clearing the reset bit, both via move and bclr, results in the bus request bit returning 1 soon thereafter. 
It seems there is still a lot left to learn about the Mega CD hardware.

[MCD Sub Stop Ins Test.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/12353261/MCD.Sub.Stop.Ins.Test.zip)

**Comment by ekeeke** [comment] 2023-08-16 06:56
Thanks for these reports, this is much appreciated.

>More curious, however, is the fact that simply resetting the sub CPU without requesting the bus appears to nevertheless trigger a bus request. Clearing the reset bit, both via move and bclr, results in the bus request bit returning 1 soon thereafter.

Well, this is how Blastem emulates it (SBRK returned value is an OR between SBRK set value and invert of SRES set value) and it kinda makes sense as this bit, when read, is supposed to reflect the state of the bus, which would be available to external device by default in case sub-cpu is in reset state. 

This would also explain why it is not recommended to use BCLR/BSET but only when modifying SRES bit to reset sub-cpu (BCLR would clear SRES bit but also set SBRQ bit so next BSET call would set both SRES and SBRQ bits, leaving sub-cpu in bus requested state)

**Comment by ekeeke** [comment] 2023-08-19 15:39
@OrionNavattan : for completeness, could you please verify if main cpu can still access PRG-RAM although bus request failed (when sub-cpu is in stopped state) ? In each 3 cases (reset only, reset+busreq, busreq only) possibly.

Thanks in advance.

**Comment by OrionNavattan** [comment] 2023-08-24 21:55
Apologies for the delay, the notification ended up in my spam folder.

Anyhow, another set of six test ROMs.

```
		move.w	#$100-1,d0	; maximum time to wait for response
	.waitsubbus:
	; Three options.
	;	move.b	#sub_reset,(mcd_reset).l			; reset sub CPU
	;	move.b	#sub_reset|sub_bus_request,(mcd_reset).l	; reset sub CPU and request bus		
		move.b	#sub_run|sub_bus_request,(mcd_reset).l		; request bus
		btst	#sub_bus_request_bit,(mcd_reset).l		; has bus request been granted?
		bne.s	.granted					; branch if so
		dbeq	d0,.waitsubbus					; if not, wait
		; Carry on even if we've timed out	

	.granted:
		clr.w	-2(sp)	; clear a word of the stack for the reset register readout
		moveq	#0,d0
		move.b	(mcd_reset).l,d0		; get reset register
		move.w	d0,-(sp)			; write to stack as word
		move.l	#'SEGA',(program_ram+$7000).l	; write 'SEGA' to program RAM
		move.l	(program_ram+$7000).l,-(sp)	; read the string from program RAM back into the stack
		illegal					; crash main CPU so we can view the stack
```

Not surprisingly, attempting to access the program RAM while sub CPU is in stopped state results in bus contention, with program RAM reads returning garbage. If we've only requested the bus, the reset bit returns 1 as expected. However, if reset has been requested, the bit returns 0, even after counting down the full $FF in the loop counter (which I'm fairly certain is longer than the time required to assert HALT and RESET for 10 clock cycles to perform a soft reset). It seems like requesting sub CPU reset also fails if the sub CPU has been halted with the stop instruction.

[MCD BRQ Test.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/12433689/MCD.BRQ.Test.zip)

**Comment by ekeeke** [comment] 2023-08-25 07:01
>Apologies for the delay, the notification ended up in my spam folder.
>Anyhow, another set of six test ROMs.

No problem, thank you for taking the time to do this.

>Not surprisingly, attempting to access the program RAM while sub CPU is in stopped state results in bus contention, with program RAM reads returning garbage.

Yes, this seemed kinda logical but it's nice to confirm it: the Mega-CD gate array probably uses busreq status bit (which is not exactly busreq bit set value, as figured above) as a switch between MD and MCD side for PRG-RAM access (this switch is somehow described in available Mega-CD manuals).

>If we've only requested the bus, the reset bit returns 1 as expected. However, if reset has been requested, the bit returns 0, even after counting down the full $FF in the loop counter (which I'm fairly certain is longer than the time required to assert HALT and RESET for 10 clock cycles to perform a soft reset). It seems like requesting sub CPU reset also fails if the sub CPU has been halted with the stop instruction.

Unless you mean you see different values being returned for the reset bit on real hardware depending on sub-cpu being stopped or not, this is expected behavior to me: reset bit read value should correspond to set value and to reset sub-cpu, you need to clear that bit then set it back to 1 for the sub-cpu to be in running state. I believe that setting that bit to 0 asserts both /RESET and /HALT inputs of sub-cpu and setting it to 1 releases them (those inputs being active low), at least this how I emulate it and it appears to work fine (CD BIOS always set reset bit back to 1 after clearing it). When read, the reset bit probably directly corresponds to the state of the /RESET line.

Now  regarding the BUSREQ bit, after looking at the schematics in available service manuals, it appears the Mega-CD gate array do not use M68K bus arbitration signals (/BR and /BGACK inputs are connected to Vcc and /BG output is left unconnected), which means it instead uses the /HALT input to halt the sub-cpu (and by extension releases the sub-cpu bus).

What probably happens is that, to determine busreq status, the Mega-CD gate array probably looks at the state of some sub-cpu signals (/AS maybe) in combination with /HALT state to determine if sub-cpu bus is released (when /HALT is asserted, 68K cpu finishes its current bus cycle before releasing the bus) but, when it is stopped state, these signals are held in a different state so the gate-array thinks the bus is still being used.

This would need to be confirmed by looking at the signals state while cpu is stopped when /HALT is asserted (or by figuring the exact logic behind the busreq bit through Mega-CD chip die analysis) but simply forcing busreq status to 0 when sub-cpu is in stopped state should be enough to emulate that behavior.

**Comment by ekeeke** [comment] 2023-08-25 14:53
Fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/dde0c09f6fdbaf0761c4c6d654feaa6604599f7b

For the record, here are the obtained results with latest build for each of the 6 last test ROMS uploaded above. This should be the same as what you see on real Mega-CD hardware (feel free to re-open the issue if this is not the case):

**MCD BRQ Test (brq reset, sub inf loop).bin**
![image](https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/8c1acdd0-a9ca-4414-8af9-da5b9102f654)

**MCD BRQ Test (brq reset, sub stop).bin**
![image](https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/6460f1f1-35c9-47d2-9517-749235908991)

**MCD BRQ Test (brq, sub inf loop).bin**
![image](https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/a8a64492-f73f-4f37-b85a-555eaee98b20)

**MCD BRQ Test (brq, sub stop).bin**
![image](https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/eba4d3cd-d834-48e1-b791-42e8714a9835)

**MCD BRQ Test (reset, sub inf loop).bin**
![image](https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/7b5023c4-e6bc-4245-a25a-a232f16efcd7)

**MCD BRQ Test (reset, sub stop).bin**
![image](https://github.com/ekeeke/Genesis-Plus-GX/assets/717091/f1455f55-8f8e-4158-9c71-36830b524cd8)

**Closed by ekeeke** 2023-08-25 14:53 UTC
Labels: enhancement, core/CD

**Comment by OrionNavattan** [comment] 2023-08-25 20:41
It looks like the latest build matches hardware behavior now. The values for the reset register in your screenshots are the same as those on both Funai and Sony Model 2s. (The bus contention garbage is different, but that probably isn't too important, so long as it's garbage returned.)

Glad I could be of help here. :>

**Comment by ekeeke** [comment] 2023-08-25 22:30
>The bus contention garbage is different, but that probably isn't too important, so long as it's garbage returned.)

Out of curiosity, what value(s) are you observing on real hardware ? Usually, "open bus" value corresponds to last value fetched on main-cpu bus, which in this case, would correspond to next main-cpu instruction due to M68K prefetch mechanism (0x4AFC = ILLEGAL)

**Comment by OrionNavattan** [comment] 2023-08-26 02:12
On both models, reading the 'SEGA' string with bus contention returns $14810300.
