### ISSUE TITLE
[Wii] Incompatible with Wiiflow Lite

### ISSUE THREAD

**Issue by Edu789** [ekeeke/Genesis-Plus-GX#357] opened 2021-03-11 10:08 UTC
When using Genesis Plus GX as a plugin in the Wiiflow Lite loader, when starting the game from the dsi error screen...

**Comment by ekeeke** [comment] 2021-03-11 12:05
Can you try the build posted here:
https://bitbucket.org/eke/genesis-plus-gx/issues/464/wii-experimental-builds-broken-wiiflow

and see if it works with your wiiflow ?

**Comment by ekeeke** [comment] 2021-03-11 20:19
Could you post a picture of the dsi error screen you got with that latest dol? It can give infos about where the program crashed.

Please use this thread to discuss your issue rather than the bitbucket thread as it is more convenient to follow the discussion in one place.

**Comment by Edu789** [comment] 2021-03-12 12:48
Ok, but it wasn't me who made this post on bitbucket ...

**Comment by Edu789** [comment] 2021-03-15 06:13
> Could you post a picture of the dsi error screen you got with that latest dol? It can give infos about where the program crashed.
> 
> Please use this thread to discuss your issue rather than the bitbucket thread as it is more convenient to follow the discussion in one place.

**Comment by Edu789** [comment] 2021-03-15 06:28
> Could you post a picture of the dsi error screen you got with that latest dol? It can give infos about where the program crashed.
> 
> Please use this thread to discuss your issue rather than the bitbucket thread as it is more convenient to follow the discussion in one place.
20210314_210933.jpg

**Comment by Edu789** [comment] 2021-03-15 06:30
> Could you post a picture of the dsi error screen you got with that latest dol? It can give infos about where the program crashed.
> 
https://github.com/Edu789/Edu/blob/9347861ee804c5cdb5cfc3f43eaa88745cb53853/20210314_210933.jpg

**Comment by Edu789** [comment] 2021-03-15 06:33
> Could you post a picture of the dsi error screen you got with that latest dol? It can give infos about where the program crashed.
> 
> Please use this thread to discuss your issue rather than the bitbucket thread as it is more convenient to follow the discussion in one place.

Dsi error screen:
https://github.com/Edu789/Edu/blob/9347861ee804c5cdb5cfc3f43eaa88745cb53853/20210314_210933.jpg

**Comment by Edu789** [comment] 2021-03-16 12:13
> Can you try the build posted here:
> https://bitbucket.org/eke/genesis-plus-gx/issues/464/wii-experimental-builds-broken-wiiflow
> 
> and see if it works with your wiiflow ?


I tested it and it didn't work ...

**Comment by Edu789** [comment] 2021-03-16 12:14
> Can you try the build posted here:
> https://bitbucket.org/eke/genesis-plus-gx/issues/464/wii-experimental-builds-broken-wiiflow
> 
> and see if it works with your wiiflow ?


I tested it and it didn't work ...

**Comment by ekeeke** [comment] 2021-03-19 13:32
Does the DSI screen you posted corresponds to the dol I posted on bitbucket ? The stack dump, which normally corresponds to a call sequence of functions, does not make any sense when I look to the map file generated for this dol. 
I suspect it is crashing while running the Wiiflow code (most likely the code responsible for loading the emulator dol then jumping to its entrypoint), not the emulator code itself so you should ask Wiiflow lite devs to analyze your exception dump and tell us where exactly it crashed and what could be the reason of the crash (badly formatted dol, invalid entrypoint, etc)

**Comment by Edu789** [comment] 2021-03-20 08:35
The dsi error screen is from the 23/02/2021 build.
It crashes when choosing the game on Wiiflow and will start.

**Comment by ekeeke** [comment] 2021-03-20 14:49
OK, I looked at the DOL file in the build repository and it indeed seems the code dump matches this DOL, which means the crash occurs in the emulator, not the loader. Unfortunately, I don't have the MAP file for this DOL anymore so I can't analyze the stack dump. Could you please try the following dol and post the DSI screen ?

[genplus_wii.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/6175807/genplus_wii.zip)

**Comment by Edu789** [comment] 2021-03-21 11:39
> OK, I looked at the DOL file in this repository (23/02/2021 build) and it looks like the code dump matches this DOL, which means the crash occurs in the emulator, not the loader. Unfortunately, I don't have the MAP file for this DOL anymore so I can't analyze the stack dump. Could you please try the following dol and post the DSI screen ?
> 
> [genplus_wii.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/6175807/genplus_wii.zip)

Yes, sure.

**Comment by Edu789** [comment] 2021-03-23 06:12
> OK, I looked at the DOL file in this repository (23/02/2021 build) and it looks like the code dump matches this DOL, which means the crash occurs in the emulator, not the loader. Unfortunately, I don't have the MAP file for this DOL anymore so I can't analyze the stack dump. Could you please try the following dol and post the DSI screen ?
> 
> [genplus_wii.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/6175807/genplus_wii.zip)

I tested and gave this Dsi error:
https://github.com/Edu789/Edu/blob/5b0a1d57424b301ab09e2362eb2b61c08593eb77/20210322_131755.jpg

**Comment by ekeeke** [comment] 2021-03-24 07:40
Looks like it is crashing in mkdir function, which is called multiple times when the application starts to create /genplus directory and all expected subdirectories (for cheats, snapshots, saves, etc) if they don't exist on SD card or USB device.

Do you use a SD card or an USB device to store the emulator and your games ? Or both ? Are any of them write-protected ? Can you see a /genplus directory and all subdirectories on them ? Maybe try to reformat your storage device as it might have been somehow corrupted, which could cause a crash when creating directories.

**Comment by Edu789** [comment] 2021-03-24 13:07
I use usb, but when I used Sd card the same problem happened, the folders in the directory are correct.
It is neither corrupted nor write protected ...

**Comment by ekeeke** [comment] 2021-03-27 14:52
I don't know what the problem is then and why it is crashing. Does the dol works correctly when loaded from Homebrew Channel ? If it loads from HBC but not from Wiiflow then it might be some specific issue caused by Wiiflow DOL loader

Also make sure the device is properly formatted to FAT32 and not some other unsupported filesystem. 

What is strange is that mkdir function should not be called if all the /genplus subfolders are actually already there like you say.
The directory structure (at the root of your usb or sdcard device) should exactly be like that by the way:
/genplus
/genplus/bios
/genplus/cheats
/genplus/cheats/cd
/genplus/cheats/gg
/genplus/cheats/md
/genplus/cheats/ms
/genplus/cheats/sg
/genplus/lock-on
/genplus/saves
/genplus/saves/cd
/genplus/saves/gg
/genplus/saves/md
/genplus/saves/ms
/genplus/saves/sg
/genplus/snaps
/genplus/snaps/cd
/genplus/snaps/gg
/genplus/snaps/md
/genplus/snaps/ms
/genplus/snaps/sg

Is any of above directory missing ?

**Comment by Edu789** [comment] 2021-03-29 11:54
Through the homebrew channel it works normally.
It is formatted in Fat32 yes.
Not this way, I will put the missing ones and test again.

**Comment by ekeeke** [comment] 2021-03-30 00:18
Ok, I think I figured where the problem comes from, it looks like a combination of a lack of robustness in devkitPPC newlib functions (mkdir in particular) that can crash under some unexpected condition and this unexpected condition being caused by WiiFlow homebrew loader when setting loaded app arguments + libfat when initialized by the loaded app.

To confirm my idea is correct, could you please try this build (with a patched libfat that ignores application path set by app loader in argv[0]) to see if it fixes the crash ?

[genplus_wii_patch1.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/6225286/genplus_wii_patch1.zip)

**Comment by Wiimpathy** [comment] 2021-03-31 09:24
You're right, it happens since those devkitPPC newlib changes. It affects retroarch too and surely other homebrews.

I've tried a workaround : https://github.com/libretro/RetroArch/commit/b5eedbaed7535e7b365287ee9194f5f9e607065c#diff-efe3891aca31b13791d89725163cf772264849f640b6a39ecc986a57e0ce4d1c

Another recent fix (maybe better but not tested) : https://github.com/libretro/RetroArch/commit/3e4aca86668a3cae189c585702c6f7042c361946

**Comment by ekeeke** [comment] 2021-03-31 12:04
Yes, it seems a simple workaround is to call chdir with either "sd:" or "usb:" as parameter to correctly set default device for newlib syscalls after having called fatInitDefault and before calling any syscall (like opendir, mkdir, etc) with a relative path as parameter.

It must be done in all homebrew that use relative paths to default FAT device though so a simpler solution might be to instead fix wiiflow plugin loader to use only exact libfat device prefixes (i e "sd:" or "usb:", not "usb1:" to "usb8:" like wiiflow does) when filling argv[0]. 

Another solution would be to fix devkitPPC newlib patch for the FindDevice function so it also returns USB mounted device id when a digit is appended to the default device name (looking at current newlib patch in devkitppc buildscripts repository, it seems it was intended to support such digit but there is some additional check added that defeats it).

**Comment by Edu789** [comment] 2021-04-01 13:33
> Ok, I think I figured where the problem comes from, it looks like a combination of a lack of robustness in devkitPPC newlib functions (mkdir in particular) that can crash under some unexpected condition and this unexpected condition being caused by WiiFlow homebrew loader when setting loaded app arguments + libfat when initialized by the loaded app.
> 
> To confirm my idea is correct, could you please try this build (with a patched libfat that ignores application path set by app loader in argv[0]) to see if it fixes the crash ?
> 
> [genplus_wii_patch1.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/6225286/genplus_wii_patch1.zip)


I tested it and the fault was corrected, it's working normally by Wiiflow ...

**Comment by Edu789** [comment] 2021-04-01 13:42
> Yes, it seems a simple workaround is to call chdir with either "sd:" or "usb:" as parameter to correctly set default device for newlib syscalls after having called fatInitDefault and before calling any syscall (like opendir, mkdir, etc) with a relative path as parameter.
> 
> It must be done in all homebrew that use relative paths to default FAT device though so a simpler solution might be to instead fix wiiflow plugin loader to use only exact libfat device prefixes (i e "sd:" or "usb:", not "usb1:" to "usb8:" like wiiflow does) when filling argv[0].
> 
> Another solution would be to fix devkitPPC newlib patch for the FindDevice function so it also returns USB mounted device id when a digit is appended to the default device name (looking at current newlib patch in devkitppc buildscripts repository, it seems it was intended to support such digit but there is some additional check added that defeats it).

**Comment by ekeeke** [comment] 2021-04-01 22:54
Ok, that's nice to know.
Could you test this new dol that tries a different solution (no patch to libfat but workaround implemented in emulator startup code) ?
[genplus_wii_patch2.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/6246827/genplus_wii_patch2.zip)

**Comment by Edu789** [comment] 2021-04-02 22:38
> Ok, so that confirms it.
> Could you test this new dol that tries a different solution (no patch to libfat but workaround implemented in emulator startup code) ?
> [genplus_wii_patch2.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/6246827/genplus_wii_patch2.zip)

I tested it and it's working too ...
The Genesis Plus when loaded by the Homebrew Channel, the cutscenes on the Sega CD work perfectly, but when loaded by the Wiiflow it gives a few crashes ...

**Comment by ekeeke** [comment] 2021-04-03 11:37
I don't understand. Which cutscenes ? In which game(s) ? Using which format (chd, cue/bin, iso/wav, iso/ogg) ?  What does 'a few crashes' means ? Random DSI exceptions as before or something else ?

You need to be more specific if you want me to investigate your issue.

**Comment by Edu789** [comment] 2021-04-03 13:32
> > The Genesis Plus when loaded by the Homebrew Channel, the cutscenes on the Sega CD work perfectly, but when loaded by the Wiiflow it gives a few crashes ...
> 
> I don't understand. Which cutscenes ? In which game(s) ? Using which format (chd, cue/bin, iso/wav, iso/ogg) ? What does 'a few crashes' means ? Random DSI exceptions as before or something else ?
> 
> You need to be more specific if you want me to investigate your issue.

In any cutscenes, use in the chd format, are not dsi errors. the game works normal...
During the cutscenes it works normally except that they give one or the other locking...

**Comment by ekeeke** [comment] 2021-04-04 07:18
>it works normally except that they give one or the other locking

Sorry but I am still not sure to understand what you are experiencing exactly :  are the games freezing at some specific (or random ?) point with the emulator still running, requiring you to reset the game through emulator menu ? or is it the emulator that is completely locked, requiring a console reboot ?

Also, what games and which part exactly ? Not all Mega CD games use cinematic or cutscene movies  and there is no flag in emulation that makes such cutscenes specially emulated or requiring specific thing: the same CD file is just being read, no matter what kind of 'scene' is occurring so if if there was a problem accessing that file because of the loader, the game would simply not start or be locked at the CD boot screen.

If your issue is that you experiencing stutters (i.e intermittent audio or video micro freezes, not complete lockup) during the playback of some scenes where the CD file is being accessed continuously (you can enable the CD leds in menu settings to see if that's the case), this might be an issue with your USB drive accesses being unstable / too slow or simply not working in USB2 mode when loaded from Wiiflow. Try putting the game on a SDHC card and loading it from here to see if this works better.

**Comment by Edu789** [comment] 2021-04-04 18:18
> > it works normally except that they give one or the other locking
> 
> Sorry but I am still not sure to understand what you are experiencing exactly : are the games freezing at some specific (or random ?) point with the emulator still running, requiring you to reset the game through emulator menu ? or is it the emulator that is completely locked, requiring a console reboot ?
> 
> Also, what games and which part exactly ? Not all Mega CD games use cinematic or cutscene movies and there is no flag in emulation that makes such cutscenes specially emulated or requiring specific thing: the same CD file is just being read, no matter what kind of 'scene' is occurring so if if there was a problem accessing that file because of the loader, the game would simply not start or be locked at the CD boot screen.
> 
> If your issue is that you experiencing stutters (i.e intermittent audio or video micro freezes, not complete lockup) during the playback of some scenes where the CD file is being accessed continuously (you can enable the CD leds in menu settings to see if that's the case), this might be an issue with your USB drive accesses being unstable / too slow or simply not working in USB2 mode when loaded from Wiiflow. Try putting the game on a SDHC card and loading it from here to see if this works better.

The game works perfectly, you don't need to reboot the console or anything like that.
The problem is only in movies and cutscenes, any game on Mega Cd has these locking problems, when started through Wiiflow, through Genesis Plus Gx started through Homebrew Channel, cutscenes and movies work perfectly without locking.
I believe the problem is with Wiiflow, because when playing Pc Engine Cd for Retroarch, the same problem happens in cutscenes, for Homebrew Channel it works perfectly ...

**Comment by ekeeke** [comment] 2021-04-04 19:28
>The game works perfectly

Let's close this issue then

**Closed** 2021-04-04 19:29 UTC
Labels: wii
