### ISSUE TITLE
Cannon Fodder glitch

### ISSUE THREAD

**Issue by Reinc01** [ekeeke/Genesis-Plus-GX#137] opened 2017-05-25 00:53 UTC
When I look at the level map at this level, and then go back to menu by pressing the Start button, the graphics become glitched. They go back to normal once I unpause the game.

https://github.com/TASVideos/BizHawk/issues/854

[cannon_fodder.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/1027649/cannon_fodder.zip)

**Comment by ekeeke** [comment] 2017-05-29 07:17
which level is this ?

**Comment by Reinc01** [comment] 2017-05-29 07:54
It's Phase 4 of Mission 23. A password will only send you to the start (Phase 1) of the mission: NJOBA.

If for some reason you can not use the movie and the save state I sent, you may want to use a walkthrough to get to Phase 3. There is also a Bizhawk movie in the thread I linked.

**Comment by ekeeke** [comment] 2017-05-29 09:03
Ok. I ended up using a Game Genie cheat to be invincible and get top the start of phase 4. I got no glitch however (using my standalone version of Genesis Plus GX) so either it's a bug caused by Bizhawk (that's often a problem when using outdated and somehow modified/customized fork of original code) or you are using a bad ROM (mine has CRC32=AD217654).

![cannon-fodder-23-4-menu](https://cloud.githubusercontent.com/assets/717091/26543380/162fb84e-445e-11e7-83c5-5f07d77ce12f.jpg)
![cannon-fodder-23-4-map](https://cloud.githubusercontent.com/assets/717091/26543378/1627017c-445e-11e7-81f8-57819590677c.jpg)
![cannon-fodder-23-4-back](https://cloud.githubusercontent.com/assets/717091/26543379/1629baf2-445e-11e7-930b-1a3b566017ab.jpg)

**Comment by ekeeke** [comment] 2017-05-29 10:06
It was not precised but I assumed the .state file was a Retroarch savestate so I loaded it using the latest core version (http://buildbot.libretro.com/nightly/windows/x86/latest/genesis_plus_gx_libretro.dll.zip).

No glitch either.

**Comment by Reinc01** [comment] 2017-05-29 11:53
I'm using the same ROM that you described (CRC32=AD217654) and I'm having this glitch both on Bizhawk and Retroarch. Save state corruption sounds unlikely for Retroarch because I used a password and got to Phase 4 quickly. What can I do to prove you that I'm seeing what I'm seeing and that it actually happens?

Here is a screenshot
![cannon fodder e 2017-05-29 18 50 55](https://cloud.githubusercontent.com/assets/6596712/26548792/131d57be-44a0-11e7-8a1a-a8cbe32d35cf.png)

**Comment by ekeeke** [comment] 2017-05-29 12:34
I don't really need 'proofs', just a way to systematically reproduce this glitch (is it even systematic or random ? relies on some specifically timed input sequence or happens no matter when you enter/exit the map ?) but since I can't  reproduce it using your retroarch state file with the latest version of the core, the cause is more likely something on your side that is misconfigured or outdated.

**Comment by Reinc01** [comment] 2017-05-29 14:14
I looked at how it goes for me once more, and this is what I see: The glitch happens whenever I use Start to close the map screen. It always happens if opening the map is the first thing I do after the level starts, so there has to be no input between the fade out of the black Briefing screen and the time you press Start during game play. You have to go to menu before the bunker on the left opens (about 4 seconds).

**Comment by ekeeke** [comment] 2017-05-29 15:20
Alright, I see it now. The key is indeed to enter the map before the bunker opens at the start of the level. If you wait for the door to open, there are no glitches. This seems like an odd timing issue , are we sure it does not happen on real hardware?

**Comment by Reinc01** [comment] 2017-05-29 17:11
I have no idea.

**Comment by ekeeke** [comment] 2017-06-05 21:58
Tested and does not happen on real hardware.
This was due to some inaccuracies left in VDP FIFO emulation which caused slight timing issue and VRAM corruption in that specific part.
This should be now fixed by https://github.com/ekeeke/Genesis-Plus-GX/commit/38ffc317cb3c75ef1002cdfb13a86503b11027d6

**Closed by ekeeke** 2017-06-05 21:58 UTC
Labels: bug
