### ISSUE TITLE
[MCD] 2M graphics operation should not be able to write to Word RAM if the MCD does not have access

### ISSUE THREAD

**Issue by Ralakimus** [ekeeke/Genesis-Plus-GX#461] opened 2022-09-13 02:57 UTC
It's been a while since I last tested this, but I believe if a graphics operation attempts to write to Word RAM in 2M mode, and it doesn't have access, it'll just wait until it has access to continue.

A few years ago, I wrote a small demo that erroneously gave the Main CPU Word RAM access after starting a graphics operation, and the result was said operation being *really* slow on hardware. The operation appeared to be allowed to continue, because I was also periodically checking if the operation was done via a command sent to the Sub CPU from the Main CPU, and the command handler I had at the time gave Sub CPU access to Word RAM every command.

**Comment by ekeeke** [comment] 2022-09-13 08:07
Yes, this is not emulated because locking 68k cpu temporary is not easy to emulate with current codebase and this was not needed by any commercial game. It appears it is needed by one game though, for which there is an issue loggued here: https://github.com/libretro/Genesis-Plus-GX/issues/33 so I will eventually add it some day. I have some working code in my private development repository but it still needs some work as it breaks other things in this game later (and maybe other games).

I am closing this as it is already addressed by [this issue](https://github.com/ekeeke/Genesis-Plus-GX/issues/408) (among many other things, this test ROM verifies access to word RAM is frozen on sub-cpu side if access is given to main-cpu)

**Comment by ekeeke** [comment] 2022-09-13 11:42
Reopened as this one is a separated issue and is more related to graphics operation access (not tested by mcd verificator test ROM) than sub-cpu access

**Comment by ekeeke** [comment] 2022-10-03 21:07
>A few years ago, I wrote a small demo that erroneously gave the Main CPU Word RAM access after starting a graphics operation, and the result was said operation being really slow on hardware.

Do you still have that demo ? I have implemented some small changes to handle this and would like to verify if it works as expected ?

**Comment by Ralakimus** [comment] 2022-10-04 01:24
[Here](https://drive.google.com/file/d/1vd7RCd3kG2tei2EddsOZursc4utf-PJD/view?usp=sharing). Don't mind the cheesy text and all that stuff, it was a birthday gift for a friend from then. They've been okay with this being shared around.

**Comment by ekeeke** [comment] 2022-10-04 22:14
This is really curious because the following code above
```
.SendWRAM2:					; Give the Main CPU Word RAM
	bset	#1,GA_MEM_MODE+1.w
	beq.s	.SendWRAM2
```

actually does NOT return Word RAM to Main CPU

Indeed, this code sets bit 1 i.e DMNA bit of memory mode register, which is not writable by Sub CPU (if you want to return Word RAM to Main CPU you need to set bit 0 i.e RET bit).

This is confirmed by running your demo in emulator because I never see Word RAM being returned to Main CPU and graphics operation is running normally despite my changes to address this issue.

This means that the slowdown on real hardware is not caused by Word RAM being returned to Main CPU during graphics operation but by DMA accessing Word RAM while it is assigned to Sub CPU. I would have thought that in this case, reading Word RAM would return garbage (or open bus) but it seems that on real hardware, Main CPU side (which includes VDP DMA) can still access Word RAM when it is assigned to Sub CPU, but if Sub CPU side (which includes graphics operation) also tries to access Word RAM at the same time, it will be delayed.

So this is actually different (and more complex) from emulating graphics operation (or Sub CPU) being halted when accessing word RAM while it is assigned to Main CPU.

**Comment by Ralakimus** [comment] 2022-10-05 00:59
Ack, curse you, old noob code. I missed that tidbit.

**Comment by ekeeke** [comment] 2022-10-05 07:09
Are you sure that linked demo runs on real hardware ? There is one test in mcd verificator that verifies writes to Word RAM from Main CPU do nothing when it is assigned to Sub CPU (it does not verify the effect of VDP DMA or Main CPU reads though).

**Comment by Ralakimus** [comment] 2022-10-05 10:13
Do forgive me for any hassle, as I've been trying to remember things from 4 years ago, and evidently, I am no good at that. I did give it a test, and indeed, it doesn't boot up on an actual MCD.

However, I also do remember fixing the boot issue and encountering this one, so I went and applied it and ran a new test, and got [this](https://youtu.be/4r5aawmyof8), which is exactly as expected.

I must have also fixed the Word RAM access bug, too. I went ahead and did that and got that tested, and ended up with [this](https://youtu.be/vXR12HNH3QI), which is exactly the behavior that I remember seeing and what I was reporting here.

**Comment by ekeeke** [comment] 2022-10-05 12:29
No problem, thanks for confirming the expected behavior for reads as well. I will test this new demo to see how it behaves in emulator.

Out of curiosity, do you remember what was the cause of the demo hanging at Sega logo ? Because it does not hang in the emulator so I'm wondering what other hardware behavior could be  unemulated or misemulated.

**Comment by Ralakimus** [comment] 2022-10-05 17:35
The cause was the Sub CPU trying to load the file into Word RAM during the Sega logo screen.

**Comment by ekeeke** [comment] 2022-10-09 08:19
https://github.com/ekeeke/Genesis-Plus-GX/commit/ea8d2991233b1eb41159eaaa955d736f5fa55752) committed to emulate GFX processing halt while word RAM is allocated to Main CPU in 2M mode.
Here is a short video capture to show the slowdown with latest demo posted above:
https://user-images.githubusercontent.com/717091/194745250-2c085b40-d696-47f0-b000-a7a45bd9ed9b.mp4

**Closed by ekeeke** 2022-10-09 08:19 UTC
Labels: enhancement, core/CD

**Comment by Ralakimus** [comment] 2022-10-09 08:41
Yup, that's basically how it should behave! Thanks!

**Comment by ekeeke** [comment] 2022-10-09 17:32
Yes, GFX processing timings are only approximated for the moment as this part is pretty much undocumented so they are probably sligthly faster than real CD hardwzre
