### ISSUE TITLE
Do you have plan for SC-3000, SF-7000, ColecoVision, MSX, Sega 32X support?

### ISSUE THREAD

**Issue by Creeper2020B** [ekeeke/Genesis-Plus-GX#457] opened 2022-08-16 14:26 UTC
@ekeeke would you like to add SC-3000, SF-7000, ColecoVision, MSX, Sega 32X support?

The file extensions: .sc, .sf7, .col, .mx1, .32x

If you don't have plan, close as not planned

**Comment by KMFDManic** [comment] 2022-08-16 14:49
@Creeper2020B here you are again, under yet another account, making the same issue post for the umpteenth time.  You've already been told many many times, yet keep trolling this repo with the same posts over and over again:)  ColecoVision has absolutely nothing to do with Genesis Plus GX.  That would be BlueMSX.  32X would be PicoDrive.

**Comment by ekeeke** [comment] 2022-08-16 14:59
Duplicate of #415 and #443

**Closed by ekeeke** 2022-08-16 14:59 UTC
