### ISSUE TITLE
Unresponsive controls in DEcap attack and japan version. 

### ISSUE THREAD

**Issue by joepogo** [ekeeke/Genesis-Plus-GX#63] opened 2015-10-27 21:56 UTC
Currently testing all files updated to source as of today. 10/27/15. Decap attack and the japanese version Magical Hat no Buttobi Tabo! Daibōken. C and start are mapped together and game has unresponsive controls. All other games are working fine, but this one is off I am getting C + Start mapped together and cannot jump at all. 

Edit: Magical hat seems to be ok now, but DEcap attack is still off. Reverting back to a previous gamepad.c and h seems to fix the issue? Is this bug, regression?

**Comment by ekeeke** [comment] 2015-10-28 13:17
Likely a regression coming from https://github.com/ekeeke/Genesis-Plus-GX/commit/1cf6882bb23190b2e82ed41d89b573d97acb7328

I remember now there was something special with this game that could screw up the controls, I will have to check it. 

Thanks for the report.

**Comment by joepogo** [comment] 2015-10-30 20:34
No problem eke, Just doing my part over here. heh. :P

**Comment by 47iscool** [comment] 2015-12-11 00:34
I was just about to open up an issue for decap but saw this, any known fix?

Is this an issue just with normal Wii port or does this affect retroarch too?

**Comment by ekeeke** [comment] 2015-12-11 07:44
I know how to fix it but had no time to properly do it yet.

As said above, it's an emulation issue related to recent changes introduced in https://github.com/ekeeke/Genesis-Plus-GX/commit/1cf6882bb23190b2e82ed41d89b573d97acb7328 so it will affect any port using up-to-date code from here.

I don't think Retroarch is synced with the last commits so it shouldn't be affected yet.

**Comment by 47iscool** [comment] 2015-12-12 22:02
Thanks for the info Eke.

**Comment by ekeeke** [comment] 2016-01-17 16:31
This has (finally) been fixed in https://github.com/ekeeke/Genesis-Plus-GX/commit/2749f1dec043ccc1dc1edc4a3aaf7e868eb471fc

Now, for the technical record: 

Decap' Attack controller code is buggy and wrongly writes 0x00 to I/O CTRL port before acquiring START & A buttons (instead of just writing to I/O DATA port and leave CTRL port untouched like all other games do), which causes TH line to be configured as an input and consequently pulled
HIGH (as verified on real hardware and now emulated by Genesis Plus GX since https://github.com/ekeeke/Genesis-Plus-GX/commit/1cf6882bb23190b2e82ed41d89b573d97acb7328), causing the controller to report B & C buttons status on TL/TR pins instead of START & A buttons.

It works on real hardware because there is some delay before TH internal state actually change from LOW to HIGH when TH pin direction is switched to input and I was able to verified with a test ROM that START & A buttons remain accessible on I/O DATA port for a few cycles before B & C buttons start being reported instead. That game accidentally takes advantage of this because it reads the I/O DATA port immediately without any delay.

**Closed by ekeeke** 2016-01-17 16:31 UTC
Labels: bug

**Comment by 47iscool** [comment] 2016-01-17 17:25
Thanks Eke.

**Comment by birdybro** [comment] 2023-01-17 13:16
[DEcapAttack_controllerFix.zip](https://github.com/ekeeke/Genesis-Plus-GX/files/10435328/DEcapAttack_controllerFix.zip)

Here's a patch for the rom that fixes the issue, from one of our MiSTer developers, in case anyone finds this issue in a random search like one of our users did. This will fix the issue on all the remaining emulators that still run into this (which some did).
